### PR TITLE
Better russian localization

### PR DESCRIPTION
**Pull request by ya-aleksko**
Fix automatic translation mistakes and make russian localization more pretty

### CODE REVIEW

**Comment by graciousgrey** [comment]
Thank you!

**Comment by graciousgrey** [comment]
Is this still work in progress?

**Comment by ya-aleksko** [comment]
> Is this still work in progress?

Yes, I forgot to rebuild translations.json, I will do it soon

**Comment by graciousgrey** [comment]
translations.json is not needed for a PR :)

**Comment by ya-aleksko** [comment]
> translations.json is not needed for a PR :)

Oh, thank you!
I sent my pull request for review

**Comment by graciousgrey** [comment]
Ah, but ru.mo is needed -  could you add that? :)

**Pull request merged**
