### PR TITLE
Search: Add option to sort results by picture title

### PR DESCRIPTION
**Pull request by wsyxbcl**
#4214

### CODE REVIEW

**Comment by lastzero** [comment]
Thanks! Let me know when it's fully tested. I'll take a look then and merge it as soon as possible.

**Comment by wsyxbcl** [comment]
> Thanks! Let me know when it's fully tested. I'll take a look then and merge it as soon as possible.

The function itself is already tested in my development environment. By "test case to cover" I mean it **probably** need to be covered in file such as folder_search_test.go as I didn't check the whole project. 

Thanks for the quick response!

**Comment by wsyxbcl** [comment]
I've reviewed the test functions and found nothing else add. The code has passed the unit tests and operates as expected in my test environment. Please proceed with your review of the code.

**Comment by lastzero** [comment]
Looks good to me! I'll go ahead and merge this for final testing. :sparkles:

**Comment by lastzero** [comment]
An updated development preview build is now available for you to test these changes:
- https://docs.photoprism.app/release-notes/#development-preview
- https://docs.photoprism.app/getting-started/updates/#development-preview

**Pull request merged**
