### PR TITLE
Changed audio conversion to only use one stream

### PR DESCRIPTION
**Pull request by ghostwheel**
`0:a` means take all audio streams of first file. 
`0:a:0 `means first stream of first file. 
`0:a:0?` means first audio stream of first file if available.
This is a fix following #3276 

Acceptance Criteria:

- [ ] Features and enhancements must be fully implemented so that they can be released at any time without additional work
- [ ] Automated unit and/or acceptance tests are mandatory to ensure the changes work as expected and to reduce repetitive manual work
- [ ] Frontend components must be responsive to work and look properly on phones, tablets, and desktop computers; you must have tested them on all major browsers and different devices
- [ ] Documentation and translation updates should be provided if needed
- [ ] In case you submit database-related changes, they must be tested and compatible with SQLite 3 and MariaDB 10.5.12+

### CODE REVIEW

**Comment by lastzero** [comment]
Thanks! Hopefully this is correct now as building a new version takes hours every time :)

**Comment by lastzero** [comment]
Do you have any sample files with multiple video streams for us? That would be really helpful.

**Comment by ghostwheel** [comment]
No, sorry. I just had problems with no audio being produced. I guess that now that I know what `-map` means, I can try to join streams from two files into one (`-map 0:v:0 -map 1:v:0` I think.) I'll try that.

**Comment by lastzero** [comment]
Just make sure this doesn't break everyone else's videos, because most people don't have multiple streams of everything... let us know when your changes are fully tested and ready to use :)

**Comment by ghostwheel** [comment]
Me neither. I don't have videos with several different streams. I think for me the added parameter `-map 0:v:0` broke things, because none of my videos had sound then when played through photoprism. So I'd be happy with not having that parameter. But if it is there, then `-map 0:a:0?` is needed to also get audio.

**Comment by lastzero** [comment]
See:
- #3284

**Pull request merged**
