### PR TITLE
Search: Basic zoom feature for Mosaic result view

### PR DESCRIPTION
**Pull request by radsto**
For the MOSAIC view only, adds a basic zoom slider on the toolbar for the following tabs : 

- Search
- Videos
- Favorites
- Calendar albums
- Private

Hi there ! I thought that would be useful because thumbs are really tiny on my huge screen. Please be kind with me since it's my first PR.

Any comments appreciated :-)

### CODE REVIEW

**Comment by graciousgrey** [comment]
We will have a look as soon as possible :). Note: This might take a few months.

**Comment by Sohalt** [comment]
I don't think it makes sense to clutter the toolbar with a slider for this, since you'll rarely adjust the thumbnail size, i.e. you'll set it once to the desired size for a screen and then leave it at that.
I think a better solution would be to use CSS media queries to query the screen size and dpi and adjust the thumbnail size based on that. That way for every screen size there would be a (hopefully) sensible default without requiring any interaction on the user's part and without cluttering the toolbar.

**Comment by inthreedee** [comment]
There are good reasons users might want to have control over the size of their thumbnails, for example accessibility reasons https://github.com/photoprism/photoprism/issues/799. Setting standard sizes based on screen resolution sounds like a nice clean solution, but ignores accessibility and personal preference.

I think a zoom slider would be a significant improvement to the photo viewing experience.

**Comment by lastzero** [comment]
@heikomat From my understanding, this would interfere with the virtualization you have added? In that case, I don't see how and when we could merge this :/

**Comment by lastzero** [comment]
I'm sorry to have to close this PR for now, as it seems we can't easily merge it. We also haven't received any feedback on the technical concerns outlined above. Should you have time to get the changes to a point where we can merge them without further refactoring and testing, feel free to reopen the PR or create a new one. Thank you very much for your contribution!

**Pull request closed without merging**
