### PR TITLE
feat: add dropzone for file uploads

### PR DESCRIPTION
**Pull request by eMerzh**
Hey, 

here is another small addition, 
a drop zone for file uploads...
it's a first version

in a future iteration i would probably like to do this directly from the photo list page, but let's start somewhere :) 

WDYT?

### CODE REVIEW

**Comment by graciousgrey** [comment]
Thank you for this pull request (as well)- we will have a look at it after our first release :)

**Review by Petru948 — APPROVED** [review]

**Comment by FunctionDJ** [comment]
😢✝️

**Comment by qlyoung** [comment]
Super interested in this! What can I do to help?

**Comment by lastzero** [comment]
Thank you so much for your contribution! I'm so sorry that we failed to merge this in time. A drop zone is a good idea and we will try to implement it ourselves.

**Pull request closed without merging**
