### PR TITLE
Add spanish translation

### PR DESCRIPTION
**Pull request by hialvaro**
I added the Spanish translation to the `frontend/src/resources/` folder. I followed this steps:

1. Go to `/frontend` run `npm run gettext-extract`
2. Open the newly created `translations.pot` file with Poedit and translate. Create a `.po` file.
3. Compile the .po file into translations.json using `npm run gettext-compile`

_PS; Sorry about two other closed pull requests, I messed up with my git config as I'm on a fresh OS installation and I hadn't configured git yet._

### CODE REVIEW

**Comment by hialvaro** [comment]
@lastzero I added a Spanish Translation

**Comment by lastzero** [comment]
Sorry, we should have merged this earlier - now there are too many changes. Is it possible that you translate it again? @graciousgrey takes care of our translations, she can answer questions if you have any :)

**Comment by hialvaro** [comment]
Yeah, I'll do it again. But when I have some free time.

**Comment by graciousgrey** [comment]
Thank you! We will let you know once we are finished with adding the translation tags to all the new stuff :)

**Comment by lastzero** [comment]
The po and mo files should be enough, `translations.*` can be created automatically and that causes the conflict.

**Comment by lastzero** [comment]
@hialvaro Added your translations manually yesterday. A few strings are missing as we've updated our UI in the meantime. But it's a start! :)

**Comment by hialvaro** [comment]
Perfect! I'll try to translate what's left later this month!

**Comment by graciousgrey** [comment]
@hialvaro we are done now with adding all translation tags. 
A few things changed: frontend translations have been moved to frontend/src/locales and we added translations for messages coming from the backend as well. 
We documented everything here: https://docs.photoprism.org/developer-guide/translations/. 
To update the already existing translations open the .po file > click "Catalogue" > "Update from POT File". 
Let us know in case something is not well explained in the documentation :)

**Comment by hialvaro** [comment]
Great! I will be doing this by the end of this month!

**Comment by hialvaro** [comment]
I made a new pull request. Closing this one.

**Pull request closed without merging**
