### PR TITLE
Config: Add regexp option to remove file sequence suffixes

### PR DESCRIPTION
**Pull request by koutloup**
This allows users to stack images that have uncommon naming extensions like IMG_1234-123

related issues: #2566, #2241

If changes are accepted, i will also update the documentation

Acceptance Criteria:

- [x] **Features and improvements are fully implemented** so that they can be released at any time without additional work
- [x] **Automated unit and/or acceptance tests have been added** to ensure the changes work as expected and to reduce repetitive manual work
- [x] Documentation has been / will be updated (specify if needed)
- [x] Contributor License Agreement (CLA) has been signed

### CODE REVIEW

**Comment by lastzero** [comment]
Thanks! Going to look into this after our vacation.

**Comment by koutloup** [comment]
> Thanks! Going to look into this after our vacation.

Hey @lastzero, i hope you had a nice vacation. Any update on this?

**Comment by graciousgrey** [comment]
There is no update yet, the implementation of the multi-user functionalities is taking all our time at the moment.

**Comment by lastzero** [comment]
@koutloup Thanks again for your contribution and my apologies for the delay! Reviewing and testing might take longer, as we need to evaluate all performance and testability implications. I'm also not entirely sure if the resulting regex isn't too complex for most users (and developers), which could lead to hard-to-find bugs. Please let us know if we should try it anyway. In this case, it also seems necessary to resolve some conflicts before we can merge the changes.

**Comment by lastzero** [comment]
I'm sorry to have to close this PR for now, as we cannot easily merge it and have not received any feedback on the above questions and concerns. Thank you very much for your contribution!

**Pull request closed without merging**
