### PR TITLE
add sql_mode in docker-compose.travis.yml

### LINKED ISSUE #79: API tests show error on Travis CI but tests are green
See https://travis-ci.org/photoprism/photoprism/jobs/466362413#L631

```
=== RUN   TestGetPhotos
--- PASS: TestGetPhotos (0.01s)
=== RUN   TestLikePhoto
(Error 1292: Incorrect datetime value: '0000-00-00' for column 'taken_at' at row 1) 
[2018-12-11 06:35:04]  
--- PASS: TestLikePhoto (0.00s)
=== RUN   TestDislikePhoto
(Error 1292: Incorrect datetime value: '0000-00-00' for column 'taken_at' at row 1) 
[2018-12-11 06:35:04]  
--- PASS: TestDislikePhoto (0.02s)
PASS
ok  	github.com/photoprism/photoprism/internal/api	0.365s
```

Maybe models are not properly initialized? Check GORM docs and compare to other code.

### PR DESCRIPTION
**Pull request by u5surf**
fix #79 

It can be avoiding the error message to add sql_mode.

https://github.com/jinzhu/gorm/issues/595

I think the message is in itself the problem of gorm.

### CODE REVIEW

**Comment by lastzero** [comment]
Thank you 👍

**Comment by lastzero** [comment]
I'd merge it, but don't see how this fixed the issue? Especially since this config file is used by Travis CI only, not real users?

**Comment by u5surf** [comment]
@lastzero Regarding this test, When TestLikePhoto runs, the database has no data for photos, it's easy to check whether has no data in db or not following patch.

```
diff --git a/internal/api/photos.go b/internal/api/photos.go
index 3526613..f4b5d64 100644
--- a/internal/api/photos.go
+++ b/internal/api/photos.go
@@ -60,9 +60,14 @@ func LikePhoto(router *gin.RouterGroup, conf photoprism.Config) {
                        c.Data(http.StatusNotFound, "image", []byte(""))
                        return
                }
+               log.Printf("Photo id: %d", photoID)
+               log.Printf("conf original path: %v", conf.OriginalsPath())
+               log.Printf("conf Db: %v", conf.Db())

                photo := search.FindPhotoByID(photoID)
+               log.Printf("photo: %v", photo)
                photo.PhotoFavorite = true
+               log.Printf("taken_at: %v", photo.TakenAt)
                conf.Db().Save(&photo)
                c.JSON(http.StatusOK, http.Response{})
        })
@@ -84,6 +89,7 @@ func DislikePhoto(router *gin.RouterGroup, conf photoprism.Config) {

                photo := search.FindPhotoByID(id)
                photo.PhotoFavorite = false
+               log.Printf("taken_at: %v", photo.TakenAt)
                conf.Db().Save(&photo)
                c.JSON(http.StatusOK, http.Response{})
        })
diff --git a/internal/api/photos_test.go b/internal/api/photos_test.go
index 2ffa18a..b1ee172 100644
--- a/internal/api/photos_test.go
+++ b/internal/api/photos_test.go
@@ -13,13 +13,14 @@ func TestGetPhotos(t *testing.T) {
        GetPhotos(router, conf)

        result := PerformRequest(app, "GET", "/api/v1/photos?count=10")
-
+       t.Log(result)
        assert.Equal(t, http.StatusOK, result.Code)
 }

 func TestLikePhoto(t *testing.T) {
        app, router, conf := NewApiTest()

+       t.Log(conf.DatabaseDsn())
        LikePhoto(router, conf)

        result := PerformRequest(app, "POST", "/api/v1/photos/1/like")
```

result:
```
go test -tags=slow -timeout 30m -coverprofile=coverage.txt -covermode=atomic -v ./internal/...
=== RUN   TestGetPhotos
--- PASS: TestGetPhotos (0.03s)
    photos_test.go:16: &{200 map[X-Result-Count:[10] X-Result-Offset:[0] Content-Type:[application/json; charset=utf-8]] [] false <nil> map[X-Result-Count:[10] X-Result-Offset:[0] Content-Type:[application/json; charset=utf-8]] true}
=== RUN   TestLikePhoto
Photo id: 1
conf original path: /go/src/github.com/photoprism/photoprism/assets/testdata/originals
conf Db: &{<nil> <nil> 0 0xc00018a000 false 0 {0xc000229ea0} <nil> {{0 0} {<nil>} map[] 0} 0xc000590420 0x14bb200 0xc00026f4e0 false}
photo: {{0 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC <nil>} 0001-01-01 00:00:00 +0000 UTC false  false        false 0 0 0 0 <nil> 0 <nil> 0 <nil>  false <nil> 0 false [] [] []}
taken_at: 0001-01-01 00:00:00 +0000 UTC

(Error 1292: Incorrect datetime value: '0000-00-00' for column 'taken_at' at row 1)
[2019-02-12 02:10:18]
--- PASS: TestLikePhoto (0.01s)
    photos_test.go:23: photoprism:photoprism@tcp(database:3306)/photoprism?parseTime=true
=== RUN   TestDislikePhoto
taken_at: 0001-01-01 00:00:00 +0000 UTC

(Error 1292: Incorrect datetime value: '0000-00-00' for column 'taken_at' at row 1)
[2019-02-12 02:10:18]
--- PASS: TestDislikePhoto (0.01s)
PASS
coverage: 45.1% of statements
...
```
` t.Log(result)`  in  photos_test.go:16 has not any photo information at all, but retesting(without `docker-compose -f docker-compose.travis.yml down`), there is different results
which it has photo information in the database

retest result:
```
$./scripts/travis.sh
scripts/download-inception.sh
Archive:  /tmp/photoprism/inception.zip
  inflating: assets/tensorflow/inception/imagenet_comp_graph_label_strings.txt
  inflating: assets/tensorflow/inception/tensorflow_inception_graph.pb
  inflating: assets/tensorflow/inception/LICENSE
go build -v ./...
...
go test -tags=slow -timeout 30m -coverprofile=coverage.txt -covermode=atomic -v ./internal/...
=== RUN   TestGetPhotos
--- PASS: TestGetPhotos (0.01s)
go test -tags=slow -timeout 30m -coverprofile=coverage.txt -covermode=atomic -v ./internal/...
=== RUN   TestGetPhotos
--- PASS: TestGetPhotos (0.01s)
    photos_test.go:16: &{200 map[X-Result-Count:[10] X-Result-Offset:[0] Content-Type:[application/json; charset=utf-8]] [{"ID":12,"CreatedAt":"2019-02-12T01:20:37Z","UpdatedAt":"2019-02-12T01:20:37Z","DeletedAt":"0001-01-01T00:00:00Z","TakenAt":"2019-02-12T01:20:36Z","PhotoTitle":"Unknown / 2019","PhotoDescription":"","PhotoArtist":"","PhotoKeywords":"","PhotoColors":"darkkhaki, dimgray, dimgrey, gray, grey, lightslategray, lightslategrey, mediumseagreen, slategray, slategrey, yellowgreen","PhotoVibrantColor":"#97c84a","PhotoMutedColor":"#6c9a68","PhotoCanonicalName":"20190212_012035_173670F4DAAF","PhotoLat":0,"PhotoLong":0,"PhotoFavorite":false,"CameraID":3,"CameraModel":"Unknown","CameraMake":"","LensID":3,"LensModel":"Unknown","LensMake":"","CountryID":"","CountryName":"","LocationID":0,"LocDisplayName":"","LocName":"","LocCity":"","LocPostcode":"","LocCounty":"","LocState":"","LocCountry":"","LocCountryCode":"","LocCategory":"","LocType":"","FileID":8,"FilePrimary":true,"FileMissing":false,"FileName":"2019/02/20190212_012035_173670F4DAAF.jpeg","FileHash":"173670f4daaf50f80ec416faabc7527f1cc22a32","FilePerceptualHash":"736e","FileType":"jpg","FileMime":"image/jpeg","FileWidth":400,"FileHeight":200,"FileOrientation":0,"FileAspectRatio":2,"Tags":""},{"ID":13,"CreatedAt":"2019-02-12T01:20:37Z","UpdatedAt":"2019-02-12T01:20:37Z","DeletedAt":"0001-01-01T00:00:00Z","TakenAt":"2019-02-12T01:20:36Z","PhotoTitle":"Unknown / 2019","PhotoDescription":"","PhotoArtist":"","PhotoKeywords":"","PhotoColors":"dimgray, dimgrey, gold, gray, greenyellow, grey, yellow","PhotoVibrantColor":"#e0ed21","PhotoMutedColor":"#977d67","PhotoCanonicalName":"20190212_012035_52FE39382A5B","PhotoLat":0,"PhotoLong":0,"PhotoFavorite":false,"CameraID":3,"CameraModel":"Unknown","CameraMake":"","LensID":3,"LensModel":"Unknown","LensMake":"","CountryID":"","CountryName":"","LocationID":0,"LocDisplayName":"","LocName":"","LocCity":"","LocPostcode":"","LocCounty":"","LocState":"","LocCountry":"","LocCountryCode":"","LocCategory":"","LocType":"","FileID":9,"FilePrimary":true,"FileMissing":false,"FileName":"2019/02/20190212_012035_52FE39382A5B.jpg","FileHash":"52fe39382a5bf94e1644020ccefbfa0c76c28180","FilePerceptualHash":"b7c2","FileType":"jpg","FileMime":"image/jpeg","FileWidth":1920,"FileHeight":1364,"FileOrientation":0,"FileAspectRatio":1.41,"Tags":""},{"ID":9,"CreatedAt":"2019-02-12T01:20:10Z","UpdatedAt":"2019-02-12T01:20:10Z","DeletedAt":"0001-01-01T00:00:00Z","TakenAt":"2018-02-26T11:37:01Z","PhotoTitle":"Tübingen / Deutschland / 2018","PhotoDescription":"","PhotoArtist":"","PhotoKeywords":"","PhotoColors":"cadetblue, dimgray, dimgrey, gray, grey, lightslategray, lightslategrey, rosybrown, royalblue, slategray, slategrey, steelblue","PhotoVibrantColor":"#3d85c3","PhotoMutedColor":"#988570","PhotoCanonicalName":"20180226_113701_A5EC95E27409","PhotoLat":48.53876111111111,"PhotoLong":9.012361111111112,"PhotoFavorite":false,"CameraID":4,"CameraModel":"iPhone SE","CameraMake":"Apple","LensID":4,"LensModel":"iPhone SE back camera 4.15mm f/2.2","LensMake":"Apple","CountryID":"de","CountryName":"Deutschland","LocationID":87793925,"LocDisplayName":"17, Geißwiesenstraße, Hagelloch, Tübingen, Landkreis Tübingen, Regierungsbezirk Tübingen, Baden-Württemberg, 72070, Deutschland","LocName":"","LocCity":"Tübingen","LocPostcode":"72070","LocCounty":"Landkreis Tübingen","LocState":"Baden-Württemberg","LocCountry":"Deutschland","LocCountryCode":"de","LocCategory":"building","LocType":"","FileID":10,"FilePrimary":true,"FileMissing":false,"FileName":"2018/02/20180226_113701_A5EC95E27409.jpg","FileHash":"a5ec95e27409938840fb1b034815301b2ad0eaa9","FilePerceptualHash":"ad73","FileType":"jpg","FileMime":"image/jpeg","FileWidth":4032,"FileHeight":3024,"FileOrientation":1,"FileAspectRatio":1.33,"Tags":"tiger cat,tübingen,landkreis tübingen,deutschland,building,tabby"},{"ID":6,"CreatedAt":"2019-02-12T01:20:06Z","UpdatedAt":"2019-02-12T01:20:06Z","DeletedAt":"0001-01-01T00:00:00Z","TakenAt":"2018-02-26T10:47:56Z","PhotoTitle":"Tabby / 2018","PhotoDescription":"","PhotoArtist":"Michael Mayer","PhotoKeywords":"","PhotoColors":"cadetblue, cornflowerblue, darkseagreen, gray, grey, lightslategray, lightslategrey, slategray, slategray, slategrey, slategrey, steelblue","PhotoVibrantColor":"#5891b7","PhotoMutedColor":"#859a65","PhotoCanonicalName":"20180226_104756_4251E5949703","PhotoLat":0,"PhotoLong":0,"PhotoFavorite":false,"CameraID":2,"CameraModel":"Canon EOS M6","CameraMake":"Canon","LensID":2,"LensModel":"EF-M22mm f/2 STM","LensMake":"","CountryID":"","CountryName":"","LocationID":0,"LocDisplayName":"","LocName":"","LocCity":"","LocPostcode":"","LocCounty":"","LocState":"","LocCountry":"","LocCountryCode":"","LocCategory":"","LocType":"","FileID":7,"FilePrimary":true,"FileMissing":false,"FileName":"2018/02/20180226_104756_4251E5949703.jpg","FileHash":"4251e59497036b6f7604da06803686465f9ce507","FilePerceptualHash":"95ca","FileType":"jpg","FileMime":"image/jpeg","FileWidth":2400,"FileHeight":1600,"FileOrientation":1,"FileAspectRatio":1.5,"Tags":"tabby,tiger cat,egyptian cat"},{"ID":11,"CreatedAt":"2019-02-12T01:20:21Z","UpdatedAt":"2019-02-12T01:20:21Z","DeletedAt":"0001-01-01T00:00:00Z","TakenAt":"2018-02-04T17:08:13Z","PhotoTitle":"Schipperke / 2018","PhotoDescription":"","PhotoArtist":"","PhotoKeywords":"","PhotoColors":"darkgoldenrod, darkseagreen, dimgray, dimgrey, gray, grey, lightslategray, lightslategrey, olive, olivedrab, rosybrown, slategray, slategrey","PhotoVibrantColor":"#978a18","PhotoMutedColor":"#938d72","PhotoCanonicalName":"20180204_170813_863A6248DCCA","PhotoLat":0,"PhotoLong":0,"PhotoFavorite":false,"CameraID":6,"CameraModel":"Canon EOS M10","CameraMake":"Canon","LensID":5,"LensModel":"EF-M15-45mm f/3.5-6.3 IS STM","LensMake":"","CountryID":"","CountryName":"","LocationID":0,"LocDisplayName":"","LocName":"","LocCity":"","LocPostcode":"","LocCounty":"","LocState":"","LocCountry":"","LocCountryCode":"","LocCategory":"","LocType":"","FileID":15,"FilePrimary":true,"FileMissing":false,"FileName":"2018/02/20180204_170813_863A6248DCCA.jpg","FileHash":"12d41cbf93a31ed99b3e11ee398d9c9b79b8b620","FilePerceptualHash":"9392","FileType":"jpg","FileMime":"image/jpeg","FileWidth":3474,"FileHeight":5208,"FileOrientation":1,"FileAspectRatio":0.67,"Tags":"schipperke"},{"ID":10,"CreatedAt":"2019-02-12T01:20:13Z","UpdatedAt":"2019-02-12T01:20:13Z","DeletedAt":"0001-01-01T00:00:00Z","TakenAt":"2014-07-17T15:42:12Z","PhotoTitle":"Neckarbrücke / Tübingen / 2014","PhotoDescription":"","PhotoArtist":"","PhotoKeywords":"","PhotoColors":"darkkhaki, goldenrod, peru","PhotoVibrantColor":"#d5d437","PhotoMutedColor":"#a69f55","PhotoCanonicalName":"20140717_154212_47ADB3C18723","PhotoLat":48.519235,"PhotoLong":9.057996666666666,"PhotoFavorite":false,"CameraID":5,"CameraModel":"Canon EOS 6D","CameraMake":"Canon","LensID":3,"LensModel":"Unknown","LensMake":"","CountryID":"de","CountryName":"Deutschland","LocationID":243480958,"LocDisplayName":"Neckarbrücke, Eberhardsbrücke, Zentrum, Universität, Tübingen, Landkreis Tübingen, Regierungsbezirk Tübingen, Baden-Württemberg, 72072, Deutschland","LocName":"Neckarbrücke","LocCity":"Tübingen","LocPostcode":"72072","LocCounty":"Landkreis Tübingen","LocState":"Baden-Württemberg","LocCountry":"Deutschland","LocCountryCode":"de","LocCategory":"highway","LocType":"bus_stop","FileID":12,"FilePrimary":true,"FileMissing":false,"FileName":"2014/07/20140717_154212_47ADB3C18723.jpg","FileHash":"8f769f435a4187d07dbcf1ed33e47d19aa119f44","FilePerceptualHash":"60b5","FileType":"jpg","FileMime":"image/jpeg","FileWidth":5472,"FileHeight":3648,"FileOrientation":1,"FileAspectRatio":1.5,"Tags":"castle,palace,highway,neckarbrücke,bus_stop,tübingen,landkreis tübingen,deutschland"},{"ID":5,"CreatedAt":"2019-02-12T01:20:04Z","UpdatedAt":"2019-02-12T01:20:04Z","DeletedAt":"0001-01-01T00:00:00Z","TakenAt":"2013-02-03T20:33:32Z","PhotoTitle":"Church / 2013","PhotoDescription":"","PhotoArtist":"","PhotoKeywords":"","PhotoColors":"brown, cadetblue, dimgray, dimgrey, firebrick, gray, grey, lightslategray, lightslategrey, sienna, slategray, slategrey","PhotoVibrantColor":"#a52d40","PhotoMutedColor":"#787888","PhotoCanonicalName":"20130203_203332_FDFA49CF0C19","PhotoLat":0,"PhotoLong":0,"PhotoFavorite":false,"CameraID":1,"CameraModel":"Canon EOS 10D","CameraMake":"Canon","LensID":1,"LensModel":"28.0-75.0 mm","LensMake":"","CountryID":"","CountryName":"","LocationID":0,"LocDisplayName":"","LocName":"","LocCity":"","LocPostcode":"","LocCounty":"","LocState":"","LocCountry":"","LocCountryCode":"","LocCategory":"","LocType":"","FileID":5,"FilePrimary":true,"FileMissing":false,"FileName":"2013/02/20130203_203332_FDFA49CF0C19.jpg","FileHash":"fdfa49cf0c19570e4148613fd4eaa74f5f3eb07e","ef95","FileType":"jpg","FileMime":"image/jpeg","FileWidth":3072,"FileHeight":2048,"FileOrientation":1,"FileAspectRatio":1.5,"Tags":"church"},{"ID":4,"CreatedAt":"2019-02-12T01:20:03Z","UpdatedAt":"2019-02-12T01:20:03Z","DeletedAt":"0001-01-01T00:00:00Z","TakenAt":"2013-02-03T20:33:22Z","PhotoTitle":"Mobile Home / 2013","PhotoDescription":"","PhotoArtist":"","PhotoKeywords":"","PhotoColors":"cadetblue, dimgray, dimgrey, gray, grey, lightslategray, lightslategrey, slategray, slategrey","PhotoVibrantColor":"","PhotoMutedColor":"#808080","PhotoCanonicalName":"20130203_203322_CC92716310EA","PhotoLat":0,"PhotoLong":0,"PhotoFavorite":false,"CameraID":1,"CameraModel":"Canon EOS 10D","CameraMake":"Canon","LensID":1,"LensModel":"28.0-75.0 mm","LensMake":"","CountryID":"","CountryName":"","LocationID":0,"LocDisplayName":"","LocName":"","LocCity":"","LocPostcode":"","LocCounty":"","LocState":"","LocCountry":"","LocCountryCode":"","LocCategory":"","LocType":"","FileID":4,"FilePrimary":true,"FileMissing":false,"FileName":"2013/02/20130203_203322_CC92716310EA.jpg","FileHash":"cc92716310ead9e8713fa2e8531b0f3185e0c819","FilePerceptualHash":"2461","FileType":"jpg","FileMime":"image/jpeg","FileWidth":3072,"FileHeight":2048,"FileOrientation":1,"FileAspectRatio":1.5,"Tags":"mobile home"},{"ID":3,"CreatedAt":"2019-02-12T01:20:02Z","UpdatedAt":"2019-02-12T01:20:02Z","DeletedAt":"0001-01-01T00:00:00Z","TakenAt":"2013-02-03T20:25:02Z","PhotoTitle":"Mobile Home / 2013","PhotoDescription":"","PhotoArtist":"","PhotoKeywords":"","PhotoColors":"dimgray, dimgrey, gray, grey, lightslategray, lightslategrey, rosybrown, slategray, slategrey","PhotoVibrantColor":"","PhotoMutedColor":"#89857a","PhotoCanonicalName":"20130203_202502_FEB94CD97B8E","PhotoLat":0,"PhotoLong":0,"PhotoFavorite":false,"CameraID":1,"CameraModel":"Canon EOS 10D","CameraMake":"Canon","LensID":1,"LensModel":"28.0-75.0 mm","LensMake":"","CountryID":"","CountryName":"","LocationID":0,"LocDisplayName":"","LocName":"","LocCity":"","LocPostcode":"","LocCounty":"","LocState":"","LocCountry":"","LocCountryCode":"","LocCategory":"","LocType":"","FileID":3,"FilePrimary":true,"FileMissing":false,"FileName":"2013/02/20130203_202502_FEB94CD97B8E.jpg","FileHash":"feb94cd97b8e762b5f15a67df65b09fd17a5e7f4","FilePerceptualHash":"ce39","FileType":"jpg","FileMime":"image/jpeg","FileWidth":2585,"FileHeight":1723,"FileOrientation":1,"FileAspectRatio":1.5,"Tags":"mobile home"},{"ID":2,"CreatedAt":"2019-02-12T01:20:01Z","UpdatedAt":"2019-02-12T01:20:01Z","DeletedAt":"0001-01-01T00:00:00Z","TakenAt":"2013-02-03T20:23:44Z","PhotoTitle":"Unknown / 2013","PhotoDescription":"","PhotoArtist":"","PhotoKeywords":"","PhotoColors":"dimgray, dimgrey, gray, grey","PhotoVibrantColor":"","PhotoMutedColor":"#987e64","PhotoCanonicalName":"20130203_202344_B928F515423A","PhotoLat":0,"PhotoLong":0,"PhotoFavorite":false,"CameraID":1,"CameraModel":"Canon EOS 10D","CameraMake":"Canon","LensID":1,"LensModel":"28.0-75.0 mm","LensMake":"","CountryID":"","CountryName":"","LocationID":0,"LocDisplayName":"","LocName":"","LocCity":"","LocPostcode":"","LocCounty":"","LocState":"","LocCountry":"","LocCountryCode":"","LocCategory":"","LocType":"","FileID":2,"FilePrimary":true,"FileMissing":false,"FileName":"2013/02/20130203_202344_B928F515423A.jpg","FileHash":"b928f515423ab059a93bccb876f3e8bbffbf1dbd","FilePerceptualHash":"4529","FileType":"jpg","FileMime":"image/jpeg","FileWidth":3072,"FileHeight":2048,"FileOrientation":1,"FileAspectRatio":1.5,"Tags":""}] false <nil> map[X-Result-Count:[10] X-Result-Offset:[0] Content-Type:[application/json; charset=utf-8]] true}
=== RUN   TestLikePhoto
Photo id: 1
conf original path: /go/src/github.com/photoprism/photoprism/assets/testdata/originals
conf Db: &{<nil> <nil> 0 0xc0001f40c0 false 0 {0xc000235ea0} <nil> {{0 0} {<nil>} map[] 0} 0xc000299550 0x14bb200 0xc0005b3080 false}
photo: {{1 2019-02-12 01:20:00 +0000 UTC 2019-02-12 01:20:00 +0000 UTC <nil>} 2013-02-03 20:23:00 +0000 UTC false Mobile Home / 2013 false    cadetblue, dimgray, dimgrey, gray, grey, lightslategray, lightslategrey, slategray, slategrey  #808080 20130203_202300_3ADE530D8413 false 0 0 51 6 <nil> 1 <nil> 1 <nil>  false <nil> 0 false [] [] []}
taken_at: 2013-02-03 20:23:00 +0000 UTC
--- PASS: TestLikePhoto (0.01s)
    photos_test.go:23: photoprism:photoprism@tcp(database:3306)/photoprism?parseTime=true
=== RUN   TestDislikePhoto
taken_at: 2013-02-03 20:23:00 +0000 UTC
--- PASS: TestDislikePhoto (0.01s)
PASS
coverage: 45.1% of statements
```
I think after TestDislikePhoto,Some tests might have stored photo informations.
therefore, there three solutions, I can be presented
- it moves api tests after photo stored tests.
- it prepares the photo information in db before this test if possible.
- it should be ignored sql known error(Error 1292: Incorrect datetime value: '0000-00-00' for column) using sql_mode.

**Comment by lastzero** [comment]
I'll close this as we should keep "sql_mode" to see errors while testing.

**Pull request closed without merging**
