### PR TITLE
Access control allow origin header

### PR DESCRIPTION
**Pull request by Daniel-H123**
Add `Access-Control-Allow-Origin` header with the app hostname to allow easier configurations with CDN url's.

As mentioned in:  #3931 

The header value is set by using this configuration:
```go
protocol + "://" + hostname: + port
```

The default header would be:
```
Access-Control-Allow-Origin: http://localhost:2342
```

Acceptance Criteria:

- [x] Features and enhancements must be fully implemented so that they can be released at any time without additional work
- [ ] Automated unit and/or acceptance tests are mandatory to ensure the changes work as expected and to reduce repetitive manual work
- [x] Frontend components must be responsive to work and look properly on phones, tablets, and desktop computers; you must have tested them on all major browsers and different devices
- [x] Documentation and translation updates should be provided if needed
- [x] In case you submit database-related changes, they must be tested and compatible with SQLite 3 and MariaDB 10.5.12+

### CODE REVIEW

**Comment by Daniel-H123** [comment]
Can you check this @lastzero

**Comment by lastzero** [comment]
@Daniel-H123 Before I merge this, I would like to read the related specs and best practices so that I have a full understanding and can update our docs accordingly. Right now, however, I need all my time to implement 2FA, OAuth2, and OIDC. Would it be ok if I take a look at this once that's done?

**Comment by Daniel-H123** [comment]
> @Daniel-H123 Before I merge this, I would like to read the related specs and best practices so that I have a full understanding and can update our docs accordingly. Right now, however, I need all my time to implement 2FA, OAuth2, and OIDC. Would it be ok if I take a look at this once that's done?

Take your time. Just wanted to confirm that it didn't end up in the void 😄 Good to see good changing coming. 2FA would be great.

**Comment by lastzero** [comment]
@Daniel-H123 see https://github.com/photoprism/photoprism/issues/3931#issuecomment-1892097223 - looking forward to your feedback on this!

**Comment by Daniel-H123** [comment]
Simular solution in https://github.com/photoprism/photoprism/commit/239708f00fc82f376e804edd27316046b6164e11

**Pull request closed without merging**
