### PR TITLE
add cuda x86_64 support

### PR DESCRIPTION
**Pull request by ossianpe**
# Changes:

These changes add Nvidia CUDA support for `x86_64` systems.

I have tested this with `CUDA 10.1` and notice a significant decrease in image import times and resources:

This is without CUDA support:
Screen Shot 2020-01-27 at 9 29 17 PM

Here is with CUDA support:
Screen Shot 2020-01-27 at 9 30 41 PM

_This was tested with the following configuration:_
```
Kubernetes 1.15 with resource limits of 12 CPU and 6GB RAM
NVIDIA-SMI 418.67
NVIDIA GeForce GTX 1070 8GB
```

# Issues:

* Labeling appears to be broken now as I do not see any labels anymore..
* Also, Tensorflow doesn't seem to want to let go of my VRAM after finishing an image import..

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:09:00.0 Off |                  N/A |
| 29%   58C    P2    44W / 151W |   7853MiB /  8119MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

# Additional information

I created a script which iterates through the Dockerfiles for `development`, and `photoprism` and dynamically builds them off settings in those files--just adding what's needed for CUDA. I'll share that too if desired.

Finally, I want to say, my intention with this PR isn't so much to have this merged into the project (right now at least), but have someone help me fix the labeling and VRAM memory consumption issues first.

### CODE REVIEW

**Comment by lastzero** [comment]
Thank you very much! Sadly, I we don't have enough donations to own GeForce test hardware, only tested it with the Nvidia Jetson and it worked (although not significantly faster than a Raspberry Pi 4).

In general, using cuda TF libs for the `photoprism` image should be enough as cuda is typically not needed for development (only for testing).

The TF log level can be changed for debugging: Simply set `TF_CPP_MIN_LOG_LEVEL` to `0` in your `docker-compose.yml`. Maybe this gives additional hints regarding VRAM usage?

**Comment by tdurieux** [comment]
Hello, 

If you want to rent a cloud based server with Nvidia graphic card. The cheapest I found is https://www.scaleway.com/en/gpu-instances/. You pay as you use and it costs 1€ per hour. It could be useful for testing.

I hope it can help you.

(I have no affiliation with them)

**Comment by lastzero** [comment]
Good idea! Maybe later since everyone is waiting for a release. We should focus on high priority issues.

**Comment by lastzero** [comment]
Are you still working on this or shall we close the pull request?

**Comment by ossianpe** [comment]
Sorry for the delay--I had lots of personal things happen (i.e. my kube system died), but! I am making some progress on this. Hopefully I'll have more to share shortly.

I'm thinking it would make sense for me to put these into respective `photoprism/docker/XXX/cuda/` folders, following the current convention. Since idk when I'll be done with this--given the issues I've been facing [that I shared in the initial PR message] I'll iterate on some scripting I used to generate these in the first place to continue upstreaming changes in the meantime.

**Comment by bandoche** [comment]
Still waiting for merge.

**Comment by lastzero** [comment]
@bandoche note the author mentioned the following issues:
- Labeling appears to be broken now as I do not see any labels anymore
- Also, Tensorflow doesn't seem to want to let go of my VRAM after finishing an image import

Advanced users can just replace the TensorFlow lib in their Docker image for hardware support. This may require compiling TensorFlow unless you find matching binaries, meaning we can't provide support for all users at the moment as our work days only have 24h minus some time for sleep.

**Comment by Mr-dbo** [comment]
Waiting for the docker version of nvidia to be available

**Comment by spacepigz** [comment]
Hello, im also trying to put my P1000 cuda processors running tensorflow.

A have complied tensorflow 1.15.2 cuda enabled, with cudnn7 and 10.0 version. 
I hit re-index for roughly 210 photos. I can confirm that the VRAM allocation is never released.
Although, I didn't lose any label.

VRAM allocation, 
```
Fri Jan  6 22:37:33 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P1000        On   | 00000000:00:11.0 Off |                  N/A |
| 34%   30C    P8    N/A /  N/A |   3996MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    301506      C   ...photoprism/bin/photoprism     3992MiB |
+-----------------------------------------------------------------------------+

```


Here are the TF logs `TF_CPP_MIN_LOG_LEVEL: 0` (removed the photoprism logs)
```
time="2023-01-06T22:07:10Z" level=info msg="indexing originals..."
time="2023-01-06T22:07:10Z" level=info msg="classify: loading nasnet"
2023-01-06 22:07:10.667485: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /opt/photoprism/assets/nasnet
2023-01-06 22:07:10.863170: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { photoprism }
2023-01-06 22:07:11.107763: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz
2023-01-06 22:07:11.108786: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f067438dbf0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-01-06 22:07:11.108838: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2023-01-06 22:07:11.111784: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2023-01-06 22:07:11.115850: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-06 22:07:11.116174: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
name: Quadro P1000 major: 6 minor: 1 memoryClockRate(GHz): 1.4805
pciBusID: 0000:00:11.0
2023-01-06 22:07:11.116578: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2023-01-06 22:07:11.119383: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2023-01-06 22:07:11.130513: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2023-01-06 22:07:11.131477: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2023-01-06 22:07:11.134900: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2023-01-06 22:07:11.137603: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2023-01-06 22:07:11.144767: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2023-01-06 22:07:11.144910: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-06 22:07:11.145228: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-06 22:07:11.145458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2023-01-06 22:07:11.145534: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2023-01-06 22:07:11.267198: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-01-06 22:07:11.267250: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0 
2023-01-06 22:07:11.267265: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N 
2023-01-06 22:07:11.267452: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-06 22:07:11.267750: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-06 22:07:11.268079: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-06 22:07:11.268291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3694 MB memory) -> physical GPU (device: 0, name: Quadro P1000, pci bus id: 0000:00:11.0, compute capability: 6.1)
2023-01-06 22:07:12.202968: I tensorflow/cc/saved_model/loader.cc:202] Restoring SavedModel bundle.
2023-01-06 22:16:58.817043: I tensorflow/cc/saved_model/loader.cc:311] SavedModel load for tags { photoprism }; Status: success. Took 588149647 microseconds.
2023-01-06 22:17:07.040485: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2023-01-06 22:17:07.194753: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2023-01-06 22:17:08.159882: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2023-01-06 22:17:08.160044: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Not found: ./bin/ptxas not found
Relying on driver to perform ptx compilation. This message will be only logged once.
2023-01-06 22:17:26.658247: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /opt/photoprism/assets/facenet
2023-01-06 22:17:26.808308: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2023-01-06 22:17:26.942894: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-06 22:17:26.943136: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
name: Quadro P1000 major: 6 minor: 1 memoryClockRate(GHz): 1.4805
pciBusID: 0000:00:11.0
2023-01-06 22:17:26.943174: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2023-01-06 22:17:26.943187: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2023-01-06 22:17:26.943198: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2023-01-06 22:17:26.943207: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2023-01-06 22:17:26.943218: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2023-01-06 22:17:26.943229: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2023-01-06 22:17:26.943240: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2023-01-06 22:17:26.943310: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-06 22:17:26.943492: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-06 22:17:26.943632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2023-01-06 22:17:26.943674: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-01-06 22:17:26.943694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0 
2023-01-06 22:17:26.943703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N 
2023-01-06 22:17:26.943799: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-06 22:17:26.944014: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-06 22:17:26.944177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3694 MB memory) -> physical GPU (device: 0, name: Quadro P1000, pci bus id: 0000:00:11.0, compute capability: 6.1)
2023-01-06 22:17:27.227940: I tensorflow/cc/saved_model/loader.cc:202] Restoring SavedModel bundle.
2023-01-06 22:17:27.228052: I tensorflow/cc/saved_model/loader.cc:212] The specified SavedModel has no variables; no checkpoints were restored. File does not exist: /opt/photoprism/assets/facenet/variables/variables.index
2023-01-06 22:17:27.228077: I tensorflow/cc/saved_model/loader.cc:311] SavedModel load for tags { serve }; Status: success. Took 569845 microseconds.

```
I can see only this warning, not sure if it's related with VRAM not being released,
```
W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Not found: ./bin/ptxas not found
Relying on driver to perform ptx compilation. This message will be only logged once
```

**Comment by lastzero** [comment]
Loading the model takes quite some time, so it's generally not unloaded when no files are being indexed for a moment. If this is a feature you need or feel is required in combination with your graphics card and other applications that are using it, feel free to check the TensorFlow API docs and suggest changes.

**Comment by lastzero** [comment]
Thank you so much for your contribution! I'll close this PR as we haven't received any feedback and I think it does pretty much the same thing as https://docs.photoprism.app/getting-started/advanced/transcoding/#nvidia-container-toolkit ? Of course to use it with TensorFlow we still need binaries that support Cuda, which we will work on when we upgrade TF.

**Pull request closed without merging**
