### PR TITLE
UX: Restore scroll position when navigating back

### PR DESCRIPTION
**Pull request by heikomat**
This is a fix for https://github.com/photoprism/photoprism/issues/2597
This also re-enables history-mode, and i think that is actually required for this fix to work, but i haven't tested it yet.

These changes do 4 things
1. Detect back-navigation, and reset remembered load-offsets if the component was navigated to without using the back-button.
This is so that not every future visit of the search-results loads hundrets/thousands of images
    - see https://github.com/photoprism/photoprism/issues/2627
2. Re-enable history-mode.
History mode was enbaled in the past and got disabled because of issues when the scroll-performance was improved. However, these issues couldn't yet be reproduced again
    - see https://github.com/photoprism/photoprism/issues/2571
    - and https://github.com/photoprism/photoprism/issues/2477
3. Disable initial search in search-view when the viewer is open (happens when returning from the download-screen in the iOS PWA)
4. After initial search, scroll to the last opened photo by remembering its `uid` in localStorage when opening the viewer.

**On back-navigation in iOS PWA-mode, the results now load enough images and auto-scroll to the last opened image.**

One known issue is that this can cause too many images to be loaded once when navigating to the search-results using the back-button without having had the image viewer open 

**You can test it wit the [`ghcr.io/heikomat/photoprism:backnav`](https://github.com/heikomat/photoprism/pkgs/container/photoprism/39385259?tag=backnav) docker image**

Acceptance Criteria:

- [x] **Features and enhancements are fully implemented** so that they can be released at any time without additional work
- [ ] **Automated unit and/or acceptance tests have been added** to ensure the changes work as expected and to reduce repetitive manual work
- [x] **User interface changes are fully responsive** and have been tested on all major browsers and various devices
- [x] Database-related changes are compatible with SQLite and MariaDB
- [x] Translations have been / will be updated (specify if needed)
- [x] Documentation has been / will be updated (specify if needed)
- [x] Contributor License Agreement (CLA) has been signed

### CODE REVIEW

**Comment by heikomat** [comment]
TODO: resetting the remembered offset happens in `search` for the photos-component, but in `created` for all other components.

It needs to happen in `search` for all components, because `search` is called by `created` AND the `$route`-watcher.
Moving it to search could prevent to many items being loaded after a filter gets applied

UPDATE: Fixed

**Comment by Rolf-Smit** [comment]
I did some quick testing with this build and this is an enormous improvement in the user experience on mobile (Android).  The back button not closing the image viewer has been my number one annoyance, seeing it working as one would expect is awesome!

Nice job!

**Comment by lastzero** [comment]
Seems this is ready for the preview so more users can test it?

**Comment by heikomat** [comment]
yes, this is ready to be tested!

**Comment by lastzero** [comment]
Shouldn't this be added to `share.js` as well so it works the same when sharing?

**Comment by heikomat** [comment]
> Shouldn't this be added to `share.js` as well so it works the same when sharing?

Could very well be. I think you're talking about the popstate-detection in `app.js`?
Should (for now) only affect scenarios where a shared album is opened in PWA mode, but having the shared-scenario work differently than the regular scenario should definitely be avoided :)

**Comment by lastzero** [comment]
> Could very well be. I think you're talking about the popstate-detection in `app.js`?

Yes, I moved the handler to `common/navigation.js` for now so that the files can be included by both. Does it make sense to use a global variable, or do you think it could/should be refactored as well?

Also, there was a question about the scrollbar in *Places*.... is this still relevant or have you found an answer yourself?

**Comment by heikomat** [comment]
> > Could very well be. I think you're talking about the popstate-detection in `app.js`?
> 
> Yes, I moved the handler to `common/navigation.js` for now so that the files can be included by both. Does it make sense to use a global variable, or do you think it could/should be refactored as well?
> 
> Also, there was a question about the scrollbar in *Places*.... is this still relevant or have you found an answer yourself?

I think a global variable makes sense, but am open to suggestions. But! It Must be registered before the router, otherwise the event handler doesn't work.

The question regarding the scrollbars was related to the Cluster-View-Feature. Not this PR

**Comment by lastzero** [comment]
Loading it at the very top :heavy_check_mark: Check the code!

**Pull request merged**
