### PR TITLE
Translations: Add Hungarian

### PR DESCRIPTION
**Pull request by attilarepka**
This PR adds both backend/frontend translation to **Hungarian** language.

**NOTE:** Went through all possible mistakes that I made, but still not 100% sure about some translations without the context.

Feel free to add some remarks, comments, if any.

### CODE REVIEW

**Comment by lastzero** [comment]
Thanks! Looks good, except  `frontend/package-lock.json` shouldn't be in this PR. Do you know how to revert / remove it?

**Comment by attilarepka** [comment]
> Thanks! Looks good, except `frontend/package-lock.json` shouldn't be in this PR. Do you know how to revert / remove it?

Sorry, removed.

**Comment by alexislefebvre** [comment]
The file `frontend/package-lock.json` has been removed, please try to restore it: `git checkout develop -- frontend/package-lock.json`. Then commit and push.

**Comment by lastzero** [comment]
Merged into develop! Thanks again 🌈  

Development Preview build is running. You can test in about an hour.

**Pull request merged**
