### PR TITLE
UX: Add preview image to the labels tab in the photo edit dialog

### PR DESCRIPTION
**Pull request by reubendowle**
This pull requests adds an image preview when editing labels.

image

This is to address this issue: https://github.com/photoprism/photoprism/issues/628

The issue points out that there is limited space for thumbnails on mobile devices, so it will be hidden on mobile devices.

Acceptance Criteria:

- [ ] Features and enhancements must be fully implemented so that they can be released at any time without additional work
- [ ] Automated unit and/or acceptance tests are mandatory to ensure the changes work as expected and to reduce repetitive manual work
- [ ] Frontend components must be responsive to work and look properly on phones, tablets, and desktop computers; you must have tested them on all major browsers and different devices
- [ ] Documentation and translation updates should be provided if needed
- [ ] In case you submit database-related changes, they must be tested and compatible with SQLite 3 and MariaDB 10.5.12+

### CODE REVIEW

**Comment by lastzero** [comment]
Thanks! We'll provide more feedback when we are back in our office.

**Comment by lastzero** [comment]
@reubendowle I'll merge this, but need to refactor it as `$isMobile` only indicates if it's a mobile browser e.g. with touch event support, so doesn't depend on the size of the browser window, which is the actual concern:
https://github.com/photoprism/photoprism/blob/84a4c3c57e8e430dbedf803e0f18071549fc9b1b/frontend/src/app.js#L64-L66

**Comment by graciousgrey** [comment]
Ideally we can also add a thumbnail to the ⚙️ tab.

**Comment by lastzero** [comment]
@graciousgrey I'll check if that's possible. It might be good to add a component for this so we don't have to copy and paste the code into each tab....

**Comment by lastzero** [comment]
Updated our release notes and the preview build, so you can test this:
- https://docs.photoprism.app/release-notes/#development-preview

**Comment by reubendowle** [comment]
> @reubendowle I'll merge this, but need to refactor it as $isMobile only indicates if it's a mobile browser e.g. with touch event support, so doesn't depend on the size of the browser window, which is the actual concern:

@lastzero personally this looks fine for me at most sizes of the browser window on PC. I guess when the width gets too narrow triggers a scrollbar:

image

image

But this is the same behavior as the details tab. So maybe it can just be left like that, and maybe remove the isMobile condition completely?

**Comment by lastzero** [comment]
I've already merged and refactored it yesterday. It's now deployed on our demo and available with our preview build.

**Comment by loulou91** [comment]
Useful feature, but (for me) the most useful would be to have it on "people" tab...

**Comment by lastzero** [comment]
@loulou91 Instead of rendering the image on each tab and thus reducing the space available for the actual content, I was thinking about a statically positioned preview e.g. in the lower left corner. However, we just merged a lot of PR and are still busy making them releasable, so this will have to wait a bit.

**Pull request merged**
