### PR TITLE
Search: Add altitude range filter

### PR DESCRIPTION
**Pull request by Gilbert32**
This pull request adds 2 search parameters, maxalt (Maximum Altitude inclusive) and minalt (Minimum Altitude inclusive).

It uses the column photos.photo_altitude to filter photos based on the specified query.
I have added the 2 parameters and basic tests based on my need, however given I don't have extensive knowledge in the photoprism source code, and go, There's the possibility I might have missed to implement it in some place in the source code.
I also added basic tests and they passed.

Acceptance Criteria:

- [x] Features and enhancements must be fully implemented so that they can be released at any time without additional work
- [x] Automated unit and/or acceptance tests are mandatory to ensure the changes work as expected and to reduce repetitive manual work
- [x] Frontend components must be responsive to work and look properly on phones, tablets, and desktop computers; you must have tested them on all major browsers and different devices
- [x] Documentation and translation updates should be provided if needed
- [x] In case you submit database-related changes, they must be tested and compatible with SQLite 3 and MariaDB 10.5.12+

### CODE REVIEW

**Comment by Gilbert32** [comment]
I have added a docs commit on my fork of photoprism-docs repository, however i'm not sure how to proceed. Should I create a PR for that if this PR was merged?

https://github.com/photoprism/photoprism-docs/compare/master...Gilbert32:photoprism-docs:feature/filter_altitude

**Comment by lastzero** [comment]
Thank you! I think it makes sense to implement this in a similar way as I've just added this:
- https://github.com/photoprism/photoprism/issues/3818

**Comment by Gilbert32** [comment]
Awesome! I will adjust my code as soon as I have free time. Until then, I'm marking the issue as not fully implemented.

**Comment by Gilbert32** [comment]
I've updated the PR, now the code uses IntRange instead of separate min and max filters.

**Comment by lastzero** [comment]
@Gilbert32 I'll merge this now, but may need to change a few details:

- From what I know, the altitude can be negative.
- The filter docs should mention that it has to be specified in meters (m).

Thank you for your contribution! :1st_place_medal:

**Pull request merged**
