### PR TITLE
Estimate album country

### PR DESCRIPTION
**Pull request by kvalev**
Estimate the country for a given album, based on the photos in the album.

### CODE REVIEW

**Comment by kvalev** [comment]
@lastzero Before I spend too much time on that (and getting up to speed with golang and the codebase), let me know whether you agree in principal with this feature.

**Comment by lastzero** [comment]
The idea is good. Should be implemented with SQL for performance reasons though, so that batch updates are possible. Looping through all photos using Go is very inefficient.

The issue here is that there may be photos from multiple countries, so you either need to weight them, set a threshold or only set a country if all photos are from the same country. Still somewhat unsolved in my brain, so not implemented yet as you can see :)

**Comment by kvalev** [comment]
I see, implementing this is SQL will be a nightmare and quite messy, so I will close this PR. There is always the option to automate this using the REST API, if someone is eager to do so.

For the actual implementation, I did it the most conservative way possible - set the country, only if all (tagged) pictures are from the same country.

**Comment by lastzero** [comment]
> I see, implementing this is SQL will be a nightmare and quite messy

Now you're exaggerating 😉

**Pull request closed without merging**
