### PR TITLE
Added ZH translation

### PR DESCRIPTION
**Pull request by ray1422**

### CODE REVIEW

**Comment by lastzero** [comment]
PRs can only be merged with a signed CLA. Let me know when you have any questions!

**Comment by ray1422** [comment]
> PRs can only be merged with a signed CLA. Let me know when you have any questions!

I've signed but it still shows not signed and I have no idea what's wrong with it :(

**Comment by ray1422** [comment]
OK, I fixed by git reset and modifing git config then force push.

**Comment by lastzero** [comment]
Thank you very much! :heart:

**Pull request merged**
