### PR TITLE
Places: Add Cluster View

### PR DESCRIPTION
**Pull request by heikomat**
This is an attempt to implement the cluster-view proposed in https://github.com/photoprism/photoprism/issues/1187

Acceptance Criteria:

- [x] **Features and improvements are fully implemented** so that they can be released at any time without additional work
- [ ] **Automated unit and/or acceptance tests have been added** to ensure the changes work as expected and to reduce repetitive manual work
- [ ] **User interface changes are fully responsive** and have been tested on all major browsers and various devices
- [ ] Database-related changes are compatible with SQLite and MariaDB
- [ ] Translations have been / will be updated (specify if needed)
- [ ] Documentation has been / will be updated (specify if needed)
- [x] Contributor License Agreement (CLA) has been signed

### CODE REVIEW

**Comment by lastzero** [comment]
@heikomat We would love to test and merge this if you think it is ready to be included in our development preview? To do this, remaining conflicts need to be resolved - hopefully just the `package-lock.json` :crossed_fingers:

**Comment by heikomat** [comment]
@lastzero github says there are no conflicts with the base branch.
give me a couple of minutes to merge develop into this branch

**Comment by reubendowle** [comment]
This is a great improvement to the places screen. I think the way the clusters are created needs a little bit of work. I tested this out centered on my house, where there are many thousand photos. I can see it creates several independent clusters of photos centered around my house.

image

The red clusters are showing photos taken in my house, but showing as two separate clusters in the same house, and one large one centered in the neighbors house.

I think perhaps there needs to be a bigger minimum radius for the clustering?

**Comment by heikomat** [comment]
@reubendowle could it be that the GPS coordinates in the pictures aren't fully accurate?

If they were shot with a Smartphone, its GPS info might have been inacurate the moment the picture was taken

**Comment by reubendowle** [comment]
> @reubendowle could it be that the GPS coordinates in the pictures aren't fully accurate?
> 
> If they were shot with a Smartphone, its GPS info might have been inacurate the moment the picture was taken

I agree that inaccurate GPS information is definitely part of the issue.

But I also think it is a bit silly to have two separate groups with 99+ photos shown in the same building - it seems like a slightly larger minimum radius for groupings would be a simple way to improve the experience here.

That said, I don't think this minor thing should prevent this change being merged - it is much better than how it works at the moment.

**Comment by lastzero** [comment]
@heikomat It seems that one of our changes has created another conflict. Once this is resolved and we have your go, I'll be happy to merge this to develop for further testing! :heart:

**Comment by heikomat** [comment]
Will mergen develop tomorrow and resolve the conflict

**Comment by lastzero** [comment]
Thank you very much! I'll merge this now and look forward to testing it on our demo :)

**Comment by heikomat** [comment]
@lastzero the conflict was super minor.
You added a `:context="context"` to the `<p-photo-toolbar` in `photos.vue`.
In my branch i made the `<p-photo-toolbar` multiline because of the number of properties (it was single-line before). That's why git couldn't auto-merge it.

You "have my go" as far as i assume this to be an all around improvement, even when it's not perfect.
Have not done any further testing in the last while though.

**Comment by lastzero** [comment]
@heikomat Would it be complicated to display the view next to (e.g. above or below) the map, so that the page is split in two sections, instead of using an overlay? That way you could see both at the same time.

**Comment by heikomat** [comment]
@lastzero i'd assume that its at least not easy. Depends on the flexebility of the `<v-dialog`-component.
You'd also have to keep in mind that having them side-by-side would be nice on widescreen, but not possible on mobile

**Comment by heikomat** [comment]
Oh, also the mosaic- and cards-view have the number of columns defined via css-selectors that base their calculations on the screen width. So this here works because the modal width is close to the screen width. Having the photos-view on half the screen would currently show way to many columns

**Comment by lastzero** [comment]
I could also imagine displaying the overlay similar to this, so that users see a bit more context in the background and the full window height can be used:

overlay

When you open issue details in the GitHub project view, these are also displayed in an overlay on the right-hand side, using (almost) the full height:

github-example

Tile width should be adjustable via CSS if needed, unless there is additional JS code that needs to be changed?

**Comment by graciousgrey** [comment]
> You "have my go" as far as i assume this to be an all around improvement, even when it's not perfect.
Have not done any further testing in the last while though.

Thank you, this is definitely a great improvement :heart: 
I will start with further testing today.

**Comment by lastzero** [comment]
I've reduced the padding in the Mosaic view to make more use of the available space, especially on mobile screens:
- #3572

**Comment by graciousgrey** [comment]
First of all - I love the clusters! It's much more fun to explore places now :)

Here are some first test results: 
1) Within the cluster window: When I type a search term and click enter the component closes instead of showing search results.
2) Within the cluster window: The filters on the extended search bar do not work.
3) When searching for e.g. flowers on places, I see clusters of only images with flowers. If I open such a cluster all images from this cluster are shown also the ones that do not contain flowers.

**Comment by loulou91** [comment]
Just made a test. Promising but there are problems of performance with the display when zooming in.
I'm using "default" map, the first steps of zooming in are very slow even lagging till a change of detail level of the map. Then it's fluent...
Not sure to be clear but it should be easy to reproduce.

**Comment by graciousgrey** [comment]
@loulou91 Do you experience this on your personal instance or our public demo? Can you confirm that you don't observe this issue with the latest stable release?

**Comment by loulou91** [comment]
Hi Theresa, I'm working on last preview release! I just went back to latest release and all was fine!
image

**Comment by lastzero** [comment]
My subjective feeling was also that it is a bit slower now than before. I suspect this could be due to the rendering of the previews on the map. Unfortunately, I probably won't have time to look into this until next week.

**Comment by loulou91** [comment]
To be clearer, till this level of details it is very slow and it lags:
image
and from this level of details, no more problem...
image

**Comment by reubendowle** [comment]
I have resolved the performance issue with this pull request https://github.com/photoprism/photoprism/pull/3577

**Comment by heikomat** [comment]
> I have resolved the performance issue with this pull request #3577

Crazy that i haven't noticed the performance issue, espacially regarding that the fix is not that hard. Well done 👍

**Comment by loulou91** [comment]
I made a pull of preview release this morning but the problem of performance is still there as I described it above.
Maybe the fix is still to be mergred in preview version?

**Comment by graciousgrey** [comment]
@loulou91 We plan to merge the changes today :) Many thanks for your help with testing!

**Comment by davidetoile** [comment]
Hey!
Thanks for this great feature. 
I have noticed that in some cases, when opening some clusters, grid of images is either empty either not corresponding to cluster count displayed…

**Pull request merged**
