### PR TITLE
Develop: Simplify mariadb service config in docker-compose files

### PR DESCRIPTION
**Pull request by grooverdan**
Acceptance Criteria:

- [ ] Features and enhancements must be fully implemented so that they can be released at any time without additional work
- [ ] Automated unit and/or acceptance tests are mandatory to ensure the changes work as expected and to reduce repetitive manual work
- [ ] Frontend components must be responsive to work and look properly on phones, tablets, and desktop computers; you must have tested them on all major browsers and different devices
- [ ] Documentation and translation updates should be provided if needed
- [X] In case you submit database-related changes, they must be tested and compatible with SQLite 3 and MariaDB 10.5.12+

The #3443 compatibility missed an important simplification, the mariadbd/mysqld was never needed on the command.

Also remove some short term support releases and substitute 10.11 as a long term support.

### CODE REVIEW

**Comment by lastzero** [comment]
Thanks! We'll try to merge this next week when we are back in our office 👍

Note that the extra compose file with the older MySQL / MariaDB versions is just for testing eg if someone reports problems with one of them. These won't be actively used for development or production.

**Comment by grooverdan** [comment]
Sure, enjoy your time off.

May as well keep them consistent and act as pseudo documentation.

**Comment by grooverdan** [comment]
only document I haven't make a PR for is the [release notes](https://github.com/photoprism/photoprism-docs/blob/master/docs/release-notes.md). May want to update them to this commit.

**Comment by lastzero** [comment]
@grooverdan Merged :) Thank you very much!

Feel free to also [take a look at the config examples](https://github.com/photoprism/photoprism/commit/fb4d99625dbcda045872d867aede5343e9f09843)  we provide to our users, for example:

- https://dl.photoprism.app/docker/docker-compose.yml
- https://dl.photoprism.app/podman/docker-compose.yml

Sources:
- https://github.com/photoprism/photoprism/tree/develop/setup/docker
- https://github.com/photoprism/photoprism/tree/develop/setup/podman

**Comment by grooverdan** [comment]
Your welcome, and I had a look. Thanks for taking the edits to the other files. Generally looks ok.

Saw armv7 there and it seems linuxserver and bitnami don't support a mariadb container of armv7.

**Pull request merged**
