### PR TITLE
French translation update, episode 2

### PR DESCRIPTION
**Pull request by jean-louis67**

### CODE REVIEW

**Comment by lastzero** [comment]
Did you update from our latest translations.pot file? Can't find any new strings in the diff 👀

**Comment by jean-louis67** [comment]
Clearly not my day!
I translated things like _No thanks_,_I'm a sponsor_,_Czech..._
I will reconsider all of this quietly, slowly, not immediately..

**Comment by lastzero** [comment]
Diff was huge, might have missed it :)

**Comment by jean-louis67** [comment]
Hello
I could not do a rebase yet. I have conflicts in all corners. I think I don't really understand what I'm doing.
On the other hand I checked that there are many differences in the .po file, for example line 1385
Is it a problem if I reopen this pull request?
And more generally, if I continue to merge instead of rebase, is that a problem for you?

**Comment by lastzero** [comment]
```
git reset --hard HEAD
```

See https://devconnected.com/how-to-git-reset-to-head/

**Comment by lastzero** [comment]
Or delete your fork and create a new one to have a fresh start :)

**Pull request closed without merging**
