### PR TITLE
Use deb.debian.org host for CDN redirection

### PR DESCRIPTION
**Pull request by rickysarraf**
As per http://deb.debian.org/ this host name mapping maps to geolocation
based hosts.

This helps it auto-detecting and redirecting to the fastest available host.

Acceptance Criteria:

- [x] **Features and improvements are fully implemented** so that they can be released at any time without additional work
- [ ] **Automated unit and/or acceptance tests have been added** to ensure the changes work as expected and to reduce repetitive manual work
- [ ] **User interface changes are fully responsive** and have been tested on all major browsers and various devices
- [ ] Database-related changes are compatible with SQLite and MariaDB
- [ ] Translations have been / will be updated (specify if needed)
- [ ] Documentation has been / will be updated (specify if needed)
- [x] Contributor License Agreement (CLA) has been signed

### CODE REVIEW

**Comment by rickysarraf** [comment]
@lastzero If you consider this PR, you'll also want to update the `photoprism:bullseye/bookworm` docker images.

**Comment by lastzero** [comment]
On https://www.debian.org/security/ they say you should use

```
deb http://security.debian.org/debian-security bullseye-security main contrib non-free
```

Did you test it with this and what is the difference?

```
deb http://deb.debian.org/debian-security bullseye-security main contrib non-free
```

**Comment by rickysarraf** [comment]
> On https://www.debian.org/security/ they say you should use
> 
> ```
> deb http://security.debian.org/debian-security bullseye-security main contrib non-free
> ```
> 
> Did you test it with this and what is the difference?
> 
> ```
> deb http://deb.debian.org/debian-security bullseye-security main contrib non-free
> ```

Even though deb.debian.org advertises of hosting `/debian-security`, that really isn't the case.

Neither of the links work:
* http://deb.debian.org/debian-security
* http://ftp.debian.org/debian-security

My understanding is that this is so because the DSA Team wants tight control of the `debian-security` service.

I have revised the PR to not change the url for the security repostiory archives

**Review by lastzero — APPROVED** [review]
Looks good to me now! Thanks a lot :)

**Comment by lastzero** [comment]
**I would greatly appreciate it if you (and other contributors) could test if everything works as expected and/or if there are more issues that should be fixed before a stable release! Thank You :)**

- As requested, all development base images in the https://hub.docker.com/r/photoprism/develop repository have been rebuilt after I merged your changes and fixed another problem in the buster/impish images that we found while testing

- A new Development Preview image based on this has just been pushed to https://hub.docker.com/r/photoprism/photoprism

**Comment by rickysarraf** [comment]
> **I would greatly appreciate it if you (and other contributors) could test if everything works as expected and/or if there are more issues that should be fixed before a stable release! Thank You :)**
> 
> * As requested, all development base images in the https://hub.docker.com/r/photoprism/develop repository have been rebuilt after I merged your changes and fixed another problem in the buster/impish images that we found while testing
> * A new Development Preview image based on this has just been pushed to https://hub.docker.com/r/photoprism/photoprism

Tested the latest `preview` image.

```
rrs@xps:.../lenovo$ docker pull photoprism/photoprism:preview                                                                                                                                     
preview: Pulling from photoprism/photoprism                                                                                                                                                       
2674c197c00a: Already exists                                                                                                                                                                      
1b8685bca34d: Pull complete                                                                                                                                                                       
863fd1d3025e: Pull complete                                                                                                                                                                       
2ddd6e011bdd: Pull complete                                                                                                                                                                       
4f4fb700ef54: Pull complete                                                                                                                                                                       
369b4f685441: Pull complete                                                                                                                                                                       
37f7eb6a2c89: Pull complete                                                                                                                                                                       
a1a32b6c5ab3: Pull complete                                                                                                                                                                       
3d986ffd6c48: Pull complete                                                                                                                                                                       
Digest: sha256:0fa22e4665f1101e3250a96332560ea0ee3590b068baf8f512137d36eab1e331                                                                                                                   
Status: Downloaded newer image for photoprism/photoprism:preview                                                                                                                                  
docker.io/photoprism/photoprism:preview                                                                                                                                                           


rrs@xps:.../lenovo$ docker run -d   --name photoprism   --security-opt seccomp=unconfined   --security-opt apparmor=unconfined   -p 2342:2342   -e PHOTOPRISM_UPLOAD_NSFW="true"   -e PHOTOPRISM_ADMIN_PASSWORD="insecure"   -v /photoprism/storage   -v ~/rrs-home/Data/Pictures:/photoprism/originals   photoprism/photoprism:preview
4e9b7fb2c6d14bb6104e4e55f85b867889978c5c02567de2c6d404f9a2ab4c12


rrs@xps:.../lenovo$ docker ps
CONTAINER ID   IMAGE                                                                                       COMMAND                  CREATED         STATUS                  PORTS                                                                     NAMES
4e9b7fb2c6d1   photoprism/photoprism:preview                                                               "/scripts/entrypoint…"   6 seconds ago   Up 5 seconds            0.0.0.0:2342->2342/tcp, :::2342->2342/tcp                                 photoprism


rrs@xps:.../lenovo$ docker exec -it -u 0 photoprism /bin/bash
root@4e9b7fb2c6d1:/photoprism# cat /etc/apt/sources.list
# deb http://snapshot.debian.org/archive/debian/20220316T000000Z bookworm main
deb http://deb.debian.org/debian bookworm main
# deb http://snapshot.debian.org/archive/debian-security/20220316T000000Z bookworm-security main
deb http://security.debian.org/debian-security bookworm-security main
# deb http://snapshot.debian.org/archive/debian/20220316T000000Z bookworm-updates main
deb http://deb.debian.org/debian bookworm-updates main


root@4e9b7fb2c6d1:/photoprism# apt update
Get:1 http://security.debian.org/debian-security bookworm-security InRelease [35.6 kB]
Get:2 http://deb.debian.org/debian bookworm InRelease [130 kB]
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [36.8 kB]
Get:4 http://deb.debian.org/debian bookworm-backports InRelease [37.0 kB]
Get:5 http://deb.debian.org/debian bookworm/non-free amd64 Packages [95.5 kB]
Get:6 http://deb.debian.org/debian bookworm/main amd64 Packages [8352 kB]
Get:7 http://deb.debian.org/debian bookworm/contrib amd64 Packages [54.9 kB]                                                                                                                     
Fetched 8742 kB in 21s (410 kB/s)                                                                                                                                                                
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
```

Thank you @lastzero

**Pull request merged**
