### PR TITLE
Album: Add selection dialog for cover image

### PR DESCRIPTION
**Pull request by BenNeumann**
I added a 'Use as album cover' button that lets you choose the cover photo for an album

### CODE REVIEW

**Comment by BenNeumann** [comment]
image

**Comment by inesctec-guilhermeamaral** [comment]
Hello @BenNeumann! Is it available for arm64 arch?

**Comment by BenNeumann** [comment]
@inesctec-guilhermeamaral this is only A feature proposal, it is not a production ready feature. I hope someone will pick it up and implement this the right way.

**Comment by inesctec-guilhermeamaral** [comment]
Ok. Hope someone implements it soon ;-)

**Comment by graciousgrey** [comment]
Thank you for your pull request. 

We know this is a highly requested feature, the related issue is already on our roadmap: https://github.com/photoprism/photoprism/issues/383

Please note that we can only merge pull requests fulfilling our acceptance criteria: https://docs.photoprism.app/developer-guide/pull-requests/

If someone wants to pick it up before we implement it: 
We can't add another item to the context menu, as this does not fit on smaller screens such as iPhone SE.

**Comment by Arnie97** [comment]
relevant: #924

**Comment by KunZhaoChristchurch** [comment]
Hi, any updates on this feature? some of the automatic cover photos are really not suitable.

**Comment by lastzero** [comment]
We agree, but our team is still the same size as 5 years ago while there are 1000x more users. Once we can afford to grow our team (meaning we get enough support from these users), we can work faster. It is desperately needed, no doubt about it.

**Comment by lastzero** [comment]
I'll close this for now as it's incomplete and we haven't received any feedback. Thank you for your contribution!

**Pull request closed without merging**
