### PR TITLE
Add (new) spanish translation

### PR DESCRIPTION
**Pull request by hialvaro**
Hola! Here's the new complete spanish translation. I think it's all right, if there's something missing I can fix it!

### CODE REVIEW

**Comment by lastzero** [comment]
Thank you very much 🙏

**Comment by hialvaro** [comment]
Spanish translation is not showing up when selecting "spanish" on the languages dropdown... :thinking: Is it a bug or there's something wrong with the translation?

**Comment by lastzero** [comment]
That's because you've been using `es_ES` instead of just `es` in the .po file. Do you want to send a quick for or shall I change it later?

**Comment by lastzero** [comment]
Fixed it :) Note that there is no Spanish translation for the backend yet!

**Pull request merged**
