### PR TITLE
Webdav: Enable originals webdav in readonly mode

### PR DESCRIPTION
**Pull request by mcfedr**
Adds a read only webdav server in readonly mode. 

Acceptance Criteria:

- [X] Features and enhancements must be fully implemented so that they can be released at any time without additional work
- [ ] Automated unit and/or acceptance tests are mandatory to ensure the changes work as expected and to reduce repetitive manual work
- [ ] Frontend components must be responsive to work and look properly on phones, tablets, and desktop computers; you must have tested them on all major browsers and different devices
- [ ] Documentation and translation updates should be provided if needed
- [ ] In case you submit database-related changes, they must be tested and compatible with SQLite 3 and MariaDB 10.5.12+

### CODE REVIEW

**Comment by mcfedr** [comment]
@CLAassistant I don't like that you have CLA on this project, it seriously undermines the open source nature of a project when participants are not contributing on an equal footing. I'd far rather have a my contribution under the same AGPL license you have the rest of the project under.

In this case, I'll sign it as its a small change and one I'm not sure you want )

**Comment by lastzero** [comment]
https://www.photoprism.app/oss/faq#cla

If you also contribute the same amount of money we spent and 5 years of your life, we have a deal.

**Comment by lastzero** [comment]
Your request should be implemented with my commit. You are welcome to test it!

**Comment by mcfedr** [comment]
@lastzero looks good, thanks for looking at it quickly! I'll pull it and have a go

**Pull request closed without merging**
