### PR TITLE
Added basic documentation wireframe for api, commands, and forms.

### PR DESCRIPTION
**Pull request by ScreamingTaco**
Before I get too deep into the project, is this the kind of thing you were looking for to get started with the docs?

Also, if you're using godoc's webserver to view it, make sure to append ?m=all to the url, as internal packages are not shown by default.

### CODE REVIEW

**Comment by lastzero** [comment]
I'm on vacation, so only some quick feedback now:

Before you commit, make sure to run `make fmt`, it should sort all import statements in alphabetical order. You ordered them manually, putting the github imports at the bottom, right?

Docs should be focused on exported functions and structs (starting with a capital letter). From what I saw, you started with the internal ones?

**Comment by ScreamingTaco** [comment]
I’ll try to keep this brief so you can enjoy your vacation :)

I’ve got go-plus installed in atom, and I think it automatically runs its own formatter on save; I can go back and fix it manually. As far as documenting the packages, I started with `internal/` because that was what was referenced in the issue, but I can do other packages too. Just let me know which ones you want documented :)

**Comment by lastzero** [comment]
With internal I mean `lowercaseFunctions()` vs `UppercaseFunctions()`, not the fact that they are in `internal`. Try GoLand :)

**Comment by ScreamingTaco** [comment]
Ok, so just to be clear, you want docs for capital letter stuff?

**Comment by lastzero** [comment]
Well, I think it makes sense as the documentation is for developers who use the package, so they can only access things that are uppercase. I can actually do without documentation at all, as I've written most of it. Thought it might be a nice first issue to get to know the code.

**Comment by ScreamingTaco** [comment]
Make sense. I’m considering becoming a more serious contributor to this project, because just from the short time I’ve been looking at the code, I’m intrigued. I’ll keep working on the docs so I can get a good feel for the code. Do you mind accepting this PR though? I’m participating in Hacktoberfest.

**Comment by lastzero** [comment]
As soon as the issues are fixed, especially "make fmt" must be run. There is no way around.

**Comment by ScreamingTaco** [comment]
Of course! Thanks a ton! You’ve been very supportive (this is my first time contributing anything other than typo fixes). I look forward to getting to contribute more in the future

**Comment by ScreamingTaco** [comment]
I’ll go ahead and close this pull request and open a new once I’ve fixed the formatting issue.

**Pull request closed without merging**
