### PR TITLE
adding danish translation

### PR DESCRIPTION
**Pull request by tcarlsen**

### CODE REVIEW

**Comment by graciousgrey** [comment]
Thank you :)

**Comment by graciousgrey** [comment]
Do you plan to translate the backend  (https://docs.photoprism.org/developer-guide/translations/#backend) as well ? :)

**Comment by tcarlsen** [comment]
@graciousgrey maybe. For now I would like to test my frontend translation on my wife and maybe add some minor fixes.. (hard to translate without knowing all the context the sentences are used in)

**Comment by graciousgrey** [comment]
Good point! We plan to provide an easier way for translations in the future, ideally with screenshots to provide some context

**Pull request merged**
