### PR TITLE
Docker compose has been rolled into the main CLI, so the hyphen is deprecated.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
```% docker-compose up -d
Docker Compose is now in the Docker CLI, try `docker compose up`
```

This should probably be propagated to all docker-compose files, but I can only test on Mac, so I only edited this one.

### CODE REVIEW

**Comment by StephenBrown2** [comment]
Can you specify that this is only for MacOS and Windows? https://github.com/docker/compose-cli/issues/1149#issuecomment-762278484, and for what version of the docker cli this is for? Looks like the message was added to docker-compose 1.28.6, but I'm still running `docker-compose version 1.28.5, build c4eb3a1f` on my Mac. I can't find mention of compose in the changelog for https://github.com/docker/cli/releases, though the docs mention it is only a tech preview: https://docs.docker.com/compose/cli-command/ and doesn't have full compatibility with `docker-compose`: https://docs.docker.com/compose/cli-command-compatibility/
> ❗ Important
> 
> The compose command in the Docker CLI is currently available as a Tech Preview. We recommend that you do not use this in production environments.

**Comment by alexislefebvre** [comment]
I think it's too early, I use Ubuntu 20.04 and the [official release channel of Docker](https://docs.docker.com/engine/install/ubuntu/) and `docker compose` doesn't work yet:

```shell
$ docker compose
docker: 'compose' is not a docker command.
See 'docker --help'
$ docker --version
Docker version 20.10.6, build 370c289
```

Updating these commands would complicate the usage because users would have to rewrite every `docker compose` command to `docker-compose`.

**Comment by ryanpcmcquen** [comment]
Hahahahaha:

https://github.com/lando/lando/issues/2962

**Comment by lastzero** [comment]
Let's wait a tiny bit until everyone has the new release. If the info message bothers you, I'm sure there is a way to disable it in the meantime.

**Comment by alexislefebvre** [comment]
Users should be able to use an alias in their shell from `docker-compose` to `docker compose` in order to use any version without seeing the message about the deprecation.

**Comment by alexislefebvre** [comment]
I stumbled upon this PR again, and I saw that it targets only the documentation for MacOS. If the last release of Docker on MacOSdeprecate `docker-compose`, then this PR can be updated.

**Comment by StephenBrown2** [comment]
Docker Compose 2.0 is still in beta, and breaks at least one `docker-compose.yml` file (the main one used for local dev at my work), so I would recommend not switching any documentation, and perhaps adding `docker-compose disable-v2` to the docs instead until it's verified that 2.0 works with this compose file.

**Comment by lastzero** [comment]
@alexislefebvre  According to my tests, the "docker compose ..." subcommands are only optional if you explicitly install the "docker-compose-plugin". It may be that some distributions and Docker Desktop do this, but in general it does not seem to be the default.

**Comment by lastzero** [comment]
I have changed this everywhere I found it. You are welcome to help me check if all changes are correct!

**Pull request closed without merging**
