### PR TITLE
Moments: Add holidays and additional pets

### PR DESCRIPTION
**Pull request by fly-man-**
* Add large Holidays
* Add assortment of pets

Acceptance Criteria:

- [x] **Features and enhancements are fully implemented** so that they can be released at any time without additional work
- [ ] **Automated unit and/or acceptance tests have been added** to ensure the changes work as expected and to reduce repetitive manual work
- [ ] **User interface changes are fully responsive** and have been tested on all major browsers and various devices
- [ ] Database-related changes are compatible with SQLite and MariaDB
- [ ] Translations have been / will be updated (specify if needed)
- [ ] Documentation has been / will be updated (specify if needed)
- [x] Contributor License Agreement (CLA) has been signed

### CODE REVIEW

**Comment by graciousgrey** [comment]
Thank you very much, we appreciate your efforts!

The idea of the moments is that they should be completely automated. I've never seen the labels (especially the ones for the holidays) come from Tensorflow or reverse geocoding. Did you manually add these to your files or where did they come from?

For holiday moments, we probably need some settings or localization as well, since not everyone celebrates Christmas or Thanksgiving.

**Comment by fly-man-** [comment]
The Holiday ones are added manually to the files, I was still hoping there would be some kind of option to be able to manually add them since they are being read from the labels that are given to the photos.

My initial idea for that would be a section where we would be able to add Moments ourselves instead of hard coding them in the source code.

**Comment by graciousgrey** [comment]
What you want to achieve sounds more like:

- https://github.com/photoprism/photoprism/issues/1431

**Comment by lastzero** [comment]
We can add "parakeet" and "gerbil" to *Pets*. A turtle is usually a wild animal (so probably in most of the pictures people have), although I know for sure that there are a few turtle lovers who have them at home (in which case this is not true, but then again, some people have a cheetah at home).

What a holiday is also depends on the culture and the region. So before we can add that, there must be a way to customize it. There are big differences between holidays e.g. in Israel, the USA and Europe, and probably Asia as well, although I am not an expert on this.

**Comment by lastzero** [comment]
@fly-man- I will merge this and then test & refactor it as needed so we can release it. You might be right that the additional holiday moment can be added safely, since it requires that the labels exist in the first place. Thank you!

**Comment by lastzero** [comment]
You can now help test this with our [preview build](https://docs.photoprism.app/getting-started/updates/#development-preview) and on our [public demo](https://demo.photoprism.app). An overview of all changes can be found in the Release Notes at [docs.photoprism.app/release-notes/#development-preview](https://docs.photoprism.app/release-notes/#development-preview).

**Pull request merged**
