### PR TITLE
Add a couple Server-Timing headers

### PR DESCRIPTION
**Pull request by benmccann**
Closes https://github.com/photoprism/photoprism/issues/945

I added for two API calls right now that are hit on the initial page load. I'm not imagining we'd add this to all API routes, but over time can add to ones that we are particularly interested in

This may help provide some more information for https://github.com/photoprism/photoprism/issues/1351

### CODE REVIEW

**Comment by graciousgrey** [comment]
Thank you :) We will have a look after our vacation!

**Comment by benmccann** [comment]
@lastzero do you have any thoughts about this one?

**Comment by lastzero** [comment]
We're currently trying to grow our team to get hold of all pull and feature requests. That reduces the time I can spend with development short-term though. Still busy answering emails.

We now have a KeyCDN account and a new bare metal server at a different provider which we can use to accelerate our demo and docs (TBD).

**Comment by lastzero** [comment]
Had a quick look. Needs to be polished before we can merge it into develop. Maybe there's a way to abstract database timing, so that not every single statement needs to be wrapped.

Makes sense to only add those headers in debug mode!?

**Comment by benmccann** [comment]
Thanks for taking a look!

It's a good idea to abstract the database timing. It looks like Gorm almost, but not quite supports doing that. I filed a feature request for it there https://github.com/go-gorm/gorm/issues/4493. For now, I've removed the database timing from this PR. I can work on adding it back as a follow up PR when Gorm supports it.

Before submitting this PR, I had also looked into whether it might be possible to do the overall timing in a middleware instead of instrumenting each call and unfortunately it's not. The issue there is that Gin won't let you write headers in middleware after `Next` is called to handle the request. I think basically the idea is that headers must be written in the response before the body is and `Next` is (or at least can be) writing the body. There might be some way of doing something really hacky where you buffer the whole body into a string or something, but basically I think Gin is written with the idea that all responses can be streamed and so I don't think there's any way to really improve this PR on that point.

I think it makes sense to always write these headers. It should be very cheap to calculate and include. When I worked at Google and LinkedIn we instrumented our servers in much heavier ways with distributed tracing tools and still served pages with very low response times. It was nice to have the info always available since you can never predict when an issue may occur.

**Comment by lastzero** [comment]
I'll close this PR for now since the CLA is not signed (we've reset the signatures), there are merge conflicts, and @benmccann probably doesn't need it anymore. Thanks a lot for your contributions!

**Pull request closed without merging**
