### PR TITLE
Batch edits

### PR DESCRIPTION
**Pull request by reubendowle**
This is an attempt to add the ability to modify all selected photos in one go. It allows:
* Adding a new label to all selected photos
* Setting the latitude & longitude on all selected photos

This is my attempt to address https://github.com/photoprism/photoprism/issues/271

This significantly improves my ability to import my large (50k photos) library into photoprism.

This is my first attempt at any project with either go or javascript, so there may be issues!

image

image

image

Acceptance Criteria:

- [ ] Features and enhancements must be fully implemented so that they can be released at any time without additional work
- [ ] Automated unit and/or acceptance tests are mandatory to ensure the changes work as expected and to reduce repetitive manual work
- [ ] Frontend components must be responsive to work and look properly on phones, tablets, and desktop computers; you must have tested them on all major browsers and different devices
- [ ] Documentation and translation updates should be provided if needed
- [ ] In case you submit database-related changes, they must be tested and compatible with SQLite 3 and MariaDB 10.5.12+

### CODE REVIEW

**Comment by dror3go** [comment]
Looks nice! I'm glad this issue gets attention.

I haven't looked at the implementation itself (no time, sorry) - how are you sending the actual edits to the server? Note that a single HTTP request per file chosen might be a problem.

I personally would expect a batch edit to use the existing pencil button to open the same editing form, with some fields being disabled or not visible, and not to add a new button to that context menu for evefy single editing option. Ofcourse, it needs to somehow clarify that this will affect X amount of photos.
What do you think?

**Comment by reubendowle** [comment]
> Looks nice! I'm glad this issue gets attention.

When I imported my huge photo library, the first question from my wife was "so how do I add a label to lots of photos". So I thought I would have a go at coding up a solution for it.

> I haven't looked at the implementation itself (no time, sorry) - how are you sending the actual edits to the server? Note that a single HTTP request per file chosen might be a problem.

I have added new API endpoints to do the batch editing which take the list of photos to change, along with the value to set. The current implementation is perhaps not as flexible as some people have been requesting, since it currently only allows adding new labels and setting the gps location.

> I personally would expect a batch edit to use the existing pencil button to open the same editing form, with some fields being disabled or not visible, and not to add a new button to that context menu for evefy single editing option. Ofcourse, it needs to somehow clarify that this will affect X amount of photos. What do you think?

I think using the existing window is not great, as it would just create confusion on what photos are being edited. Also, there are lots of fields which are not common (eg ISO), and how would you indicate to user that only some fields and not others would be applied to all photos.

Maybe a compromise might be a single new batch edit window, which had the various fields available for changing. They would start out blank, and blank fields would not be modified?

**Comment by lastzero** [comment]
@reubendowle **Thank you very much for your contribution!** I have just merged your other PR. Unfortunately, this one can't be merged easily, mainly for two reasons:

(1) All functionality needs to be fully responsive, meaning it needs to work on both small and large screens. However, the context/clipboard menu becomes too large this way, especially since there are many more fields that users will want to edit (so we need to find another approach)

(2) Similarly, adding a new dialog for each field does not scale well, meaning that the maintenance and testing overhead would increase significantly with each new batch edit dialog.

Because of this, I see no other option but to come up with a different UX approach. We may even need to test different solutions to gain enough confidence. Ideally, we can offer a single responsive dialog that works on mobile phones and desktop computers.

**Comment by lastzero** [comment]
Since we unfortunately can't merge it at the moment for the reasons mentioned above, I'm closing this PR. Once we have a better idea of how Batch Edit can be implemented (given the constraints), we may come back to your changes to see if they can be integrated.

**Pull request closed without merging**
