### PR TITLE
Modify ffmpeg calls to select first video stream only

### PR DESCRIPTION
**Pull request by MEDumont**
When I upgraded my phone to the Google Pixel 7, I noticed that the videos it takes have an extra video stream in them for their compressed HVC1 implementation. This means that all software transcoding of that format would result in an unplayable video file, as it was transcoding the wrong video stream (likely a second stream of parity or difference data). This alteration fixed the issue for me, and will likely avoid video files with multiple video streams causing issues in the future.

image

Acceptance Criteria:

- [x] Features and enhancements must be fully implemented so that they can be released at any time without additional work
- [x] Automated unit and/or acceptance tests are mandatory to ensure the changes work as expected and to reduce repetitive manual work
- [x] Frontend components must be responsive to work and look properly on phones, tablets, and desktop computers; you must have tested them on all major browsers and different devices
- [x] Documentation and translation updates should be provided if needed
- [x] In case you submit database-related changes, they must be tested and compatible with SQLite 3 and MariaDB 10.5.12+

### CODE REVIEW

**Comment by lastzero** [comment]
Thank you! Looks good to me based on what I've found in the FFmpeg docs:
- https://trac.ffmpeg.org/wiki/Map

I'll merge this, assuming you have tested it with a few different samples so existing functionality doesn't break?

**Comment by kvalev** [comment]
I can confirm that it works - I am using this fix for the last year or so and I havent had any problems so far

**Comment by ghostwheel** [comment]
@MEDumont , could you provide a sample video file? Is it always stream 1 (0) that should be played?
Thanks!

**Comment by MEDumont** [comment]
So upon giving it more test files, I realized that the code I provided was incomplete. It works for my purposes: the videos with no sound that accompany google motion photos, but it does not work for videos with sound. I have fixed it in my local with another minor code change that I will turn into another PR.
Here are the test files.

https://user-images.githubusercontent.com/7817161/225480251-c53d559b-7045-40c9-8543-d1a36f5c5d82.mp4


https://user-images.githubusercontent.com/7817161/225480262-0f9ffbd8-d10a-4c7e-935c-21ca001f93db.mp4

**Comment by MEDumont** [comment]
Ahh, I see lastzero beat me to it! Awesome that the ffmpeg selection is now configurable!

**Pull request merged**
