### PR TITLE
Fix example configuration for Apache 2.4

### PR DESCRIPTION
**Pull request by OliveiraHermogenes**
The tutorial on serverlab.ca contains some errors (as pointed out in the comments section there). The official docs are accurate and seem to be more helpful. I also added a reminder for the benefit of people mindlessly copying and pasting. I can confirm that the current sample configuration does not work on Apache 2.4 and that the proposed changes fix it.

### CODE REVIEW

**Comment by lastzero** [comment]
Thanks for your PR! If you sign the CLA, I'd be happy to merge this. It's part of our workflow although you just updated the docs and didn't submit code.

**Comment by OliveiraHermogenes** [comment]
Done.

I didn't sign it before because CLAassistant wanted read and **write** access to parts of my GitHub account in order for me to do so. This may be a deterrent for tiny occasional contributions such as this one. But hey, your project, your rules.

**Comment by alexislefebvre** [comment]
You can revoke access to CLAassistant once you used it. On this page: https://github.com/settings/applications

**Comment by lastzero** [comment]
Thank you!

**Pull request merged**
