### PR TITLE
Random photos sorting

### PR DESCRIPTION
**Pull request by kvalev**
related to #153

### CODE REVIEW

**Comment by graciousgrey** [comment]
Thank you, we will have a look as soon as possible :)

**Comment by lastzero** [comment]
How does this work with count and offset? Did you test it with MariaDB and SQLite?

Users typically expect results not to repeat even if they are random...

**Comment by dror3go** [comment]
For MySQL, a random `seed` should be generated and passed to the `RAND()` function.
AFAIK, SQLite doesn't support a seed for its `RANDOM()` function.

**Comment by alexislefebvre** [comment]
@kvalev why did you close this PR? You can leave it open, it will be treated at some point.

**Comment by orisdorch** [comment]
Looks like this was perhaps closed due to https://github.com/kvalev/photoprism/pull/13 ?

**Comment by lastzero** [comment]
Yes, we just don't have enough resources to work on all 200+ issues at the same time... Doing our best! 👍

**Comment by lastzero** [comment]
Random sorting must work on all databases and without breaking stacks. So it turned out to be more work. Thanks for sponsoring us! 🌈

**Comment by orisdorch** [comment]
You guys are doing awesome work - glad to contribute in some small way.. How many DBs are you supporting? It looks like the initial approach attempted to leverage each database's randomization function for the sort.. Would it make more sense to add a new field like photos.photo_randomid so you could simply sort by this field rather than using each database's randomization function? Then you could also start at a random number between 1 and max(photos.photo_randomid), so it wouldn't always start at photos.photo_randomid = 1..

It may be a pain to ensure uniqueness of randomized IDs - if you could randomly reorder a series of numbers between 1 and length(photos), then append them sequentially to photos.photo_uid (i.e. if a randomized list of 1 to 4 is '3,2,4,1', these values would sequentially associated with uids '1,2,3,4').. I imagine a randomizer job that would populate entries with null photos.photo_randomid after the indexer runs, perhaps with the possibility or re-randomizing everything as a seperate job.. 

Code I saw in the prior attempt at randomized sort:
```
	case entity.SortOrderRandom:
		switch DbDialect() {
		case MySQL:
			s = s.Order("RAND()")
		case SQLite:
			s = s.Order("RANDOM()")
		default:
			err := fmt.Errorf("unknown sql dialect %s", DbDialect())
			log.Errorf("photos: %s", err)
			return results, 0, err
		}
	default:
		s = s.Order("taken_at DESC, photos.photo_uid, files.file_primary DESC")
```

**Comment by gerroon** [comment]
Is this implemented?

**Comment by graciousgrey** [comment]
@gerroon No,  it was closed by the contributor before it was fully implemented and tested. The related issue is still open: #153 

Because we want to create the best possible product for our users, we have a set of guidelines which ensure that all source code contributions are acceptable:

- The feature must be fully implemented
- Unit and acceptance tests have to be written
- The feature must work with sqlite and mysql
- The UI must be fully responsive
- It needs to be tested on multiple browsers and devices
- Translations need to be created for all languages
- Docs need to be updated

**Comment by lastzero** [comment]
Note that we have added support for a "random" sort order to our backend API, see https://github.com/photoprism/photoprism/commit/47defc861c17ca1348eb0193b9ea84ce2708f228.

**Comment by kvalev** [comment]
> How does this work with count and offset? Did you test it with MariaDB and SQLite?
> 
> Users typically expect results not to repeat even if they are random...

For documentation purposes, I have to mention that the current implementation also suffers from this problem, so as a user dont be surprised if you see a bunch of repeating photos.

**Comment by lastzero** [comment]
See:
- https://github.com/photoprism/photoprism/issues/153#issuecomment-1408480166

**Pull request closed without merging**
