### PR TITLE
H265 encoded videos in Safari

### PR DESCRIPTION
**Pull request by andr-ec**
This pull request is based on the discussion in https://github.com/photoprism/photoprism/issues/440

This pull request allows Safari to play H265 encoded videos.

The header needs to be included because Safari uses byte range requests and if it is not included the MIME type will be application/octet-stream, which Safari doesn't recognize as a video format.

### CODE REVIEW

**Comment by graciousgrey** [comment]
Thank you for your pull request! At the moment we are super busy but we will come back to it as soon as we find time to see why the build is failing :)

**Comment by acarrera94** [comment]
Anything I need to do to have this accepted? Thanks!

**Comment by lastzero** [comment]
Need to check why the build was failing, hopefully get to this on the weekend. Might be a JS issue you need to fix.

As our focus is on a stable release, we also tend to keep changes back (for later) that might introduce new issues or require significant testing.

**Comment by acarrera94** [comment]
Failed on the deploy section. Any idea what this means? 
```
+ scripts/docker-login.sh
--
2 | Error: Cannot perform an interactive login from a non TTY device

```

**Comment by benmccann** [comment]
@acarrera94 this PR will need to be rebased. Doing so may also help with your build failure since I don't see recent PRs having the failure you mentioned

**Comment by ark-** [comment]
Hmm I guess this is why videos don't play on my phone and laptop. Just get an empty space where the video should be after I click "play".

**Comment by lastzero** [comment]
Why is it still marked as "work in progress"? If it's a quick win and well tested, we can merge this soon.

**Comment by GewoonJaap** [comment]
Is there a way we can fix the merge conflicts? Since this branch belongs to @acarrera94

> 
> 
> Why is it still marked as "work in progress"? If it's a quick win and well tested, we can merge this soon.

**Comment by andr-ec** [comment]
Closing in favor of https://github.com/photoprism/photoprism/pull/2379

**Pull request closed without merging**
