### PR TITLE
First implementation of liking a photo

### PR DESCRIPTION
**Pull request by philnate**
Basic implementation for photo liking, yet missing tests (to be added).

### CODE REVIEW

**Comment by lastzero** [comment]
Cool, thanks! I'll review it ASAP - attending a conference today.

**Comment by lastzero** [comment]
Looks good on the first sight! Cool. We'll need tests for this though.
 
Tests for other routes are also missing, feel free to add them while you're at it.

**Comment by lastzero** [comment]
Going to merge this now in case you're participating in the Hacktoberfest. In the future, we will make sure only code with tests gets merged.

**Comment by philnate** [comment]
Will open another PR with tests for the stuff added here.

**Pull request merged**
