### PR TITLE
Remove unused npm packages

### PR DESCRIPTION
**Pull request by benmccann**
I didn't see anything importing any of these packages

### CODE REVIEW

**Comment by benmccann** [comment]
Hmm. The go tests are failing a database migration. No idea why...

**Comment by lastzero** [comment]
Not your fault... disk was full on our build server 👀

**Comment by lastzero** [comment]
`puppeteer-core` might be needed for our acceptance tests? @graciousgrey

**Comment by benmccann** [comment]
I don't think it would be, but I can't get the acceptance tests to run even on `develop`.

The developer guide says to run `make acceptance`, but that doesn't work for me:
```
$ make acceptance
Running JS acceptance tests in Chrome...

> photoprism@1.0.0 acceptance /home/bmccann/src/photoprism/frontend
> testcafe "chromium:headless --disable-dev-shm-usage" --skip-js-errors --selector-timeout 5000 -S -s tests/screenshots tests/acceptance

ERROR Unable to find the browser. "chromium:headless --disable-dev-shm-usage" is not a browser alias or path to an executable file.
```

I tried running `npm run acceptance-local` and that did run `testcafe`, but still failed:
```
      A request to "http://localhost:2343/photos" has failed.
      Use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".
      
      Error details:
      Failed to find a DNS-record for the resource at "http://localhost:2343/photos".
```

I have a PhotoPrism server running on `localhost`. Am I supposed to kill it before running the tests or does it need to be up and running for `testcafe` to access?

**Comment by graciousgrey** [comment]
Good point. You are right the docs are not up to date!

Regarding the error you get for `make acceptance ` --> It seems like chromium is not installed in the container I am not sure why.

The other error is due to the fact that the instance is not running. 
You need to run make `acceptance all` or `make acceptance-start` and then `make acceptance` BUT at the moment all tests would fail for you as a special set of files in the storage directory is needed. We do not push them. 

Tests are on my list for next week anyway. 
I need to check some things first but then I add the files to our download server, so that they can be downloaded by developers that want to run tests locally.  I will also update the docs accordingly.

Another open to do is including them into our CI flow, we just did not find time yet.

**Comment by graciousgrey** [comment]
@benmccann docu is updated https://docs.photoprism.org/developer-guide/tests/  and the files needed for testing can be downloaded now.

**Comment by benmccann** [comment]
I've rebased this PR. The acceptance test failures don't seem related to this PR. If you're able to get them to run you could probably verify

The acceptance tests still fail for me. I'm guessing it's because I got some errors when starting the server:
```
# make acceptance-restart
go: downloading golang.org/x/sys v0.0.0-20210110051926-789bb1bd4061
go: downloading github.com/klauspost/cpuid/v2 v2.0.3
go: downloading github.com/gin-contrib/gzip v0.0.3
go: downloading github.com/ugorji/go v1.2.3
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/ugorji/go/codec v1.2.3
go: downloading github.com/go-playground/validator/v10 v10.4.1
go: downloading github.com/leodido/go-urn v1.2.1
INFO[2021-01-15T23:06:04Z] looking for pid in /go/src/github.com/photoprism/photoprism/storage/photoprism.pid 
FATA[2021-01-15T23:06:04Z] open /go/src/github.com/photoprism/photoprism/storage/photoprism.pid: no such file or directory 
exit status 1
cp: cannot stat 'storage/acceptance/backup.db': No such file or directory
cp: cannot stat 'storage/acceptance/config/settingsBackup.yml': No such file or directory
DEBU[2021-01-15T23:06:11Z] config: running on “Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz” 
DEBU[2021-01-15T23:06:11Z] config: created /go/src/github.com/photoprism/photoprism/storage/acceptance/config/settings.yml  
DEBU[2021-01-15T23:06:11Z] requesting api key for maps & places from hub.photoprism.app 
INFO[2021-01-15T23:06:15Z] closed database connection                   
INFO[2021-01-15T23:06:15Z] daemon started with process id 23919         
```

**Comment by lastzero** [comment]
Thank you very much! :heart: 

I'll merge this. We'll see what happens.

**Pull request merged**
