### PR TITLE
API: Expose Prometheus-style metrics endpoint

### PR DESCRIPTION
**Pull request by brandon1024**
# Summary

Expose a new API which can be scraped by prometheus to gather useful metrics from an instance. The new endpoint exposes photoprism build version information, golang version, edition and various count metrics.

Related to https://github.com/photoprism/photoprism/issues/213

## Additional Info

Prometheus-style metrics exposition is a feature I've wanted for a little while now. I saw there was some discussion in #213 around this, so I thought I'd take a stab at implementing it. Hopefully this serves as a good starting point--we can enhance or tweak the exposed metrics if needed :-)

Here's a sample output:

```
$ curl localhost:2342/api/v1/metrics
*   Trying ::1:2342...                                                                                                                                                                                                                                                      
* connect to ::1 port 2342 failed: Connection refused                                                                                                                                                                                                                       
*   Trying 127.0.0.1:2342...                                                                                                          
* Connected to localhost (127.0.0.1) port 2342 (#0)
> GET /api/v1/metrics HTTP/1.1               
> Host: localhost:2342                                                                                                                
> User-Agent: curl/7.74.0              
> Accept: */*                            
>                                                                                                                                     
* Mark bundle as not supporting multiuse     
< HTTP/1.1 200 OK                                      
< Content-Security-Policy: frame-ancestors 'none';               
< X-Frame-Options: DENY                 
< Date: Sat, 25 Feb 2023 15:09:49 GMT
< Content-Type: text/plain; charset=utf-8                
< Transfer-Encoding: chunked            
<
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 1.0394e-05
go_gc_duration_seconds{quantile="0.25"} 1.9995e-05
go_gc_duration_seconds{quantile="0.5"} 5.2493e-05
go_gc_duration_seconds{quantile="0.75"} 0.000184451
go_gc_duration_seconds{quantile="1"} 0.000211067
go_gc_duration_seconds_sum 0.000695965
go_gc_duration_seconds_count 8
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 25
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.20.1"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 5.086684e+07
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 1.77132296e+08
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 31221
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 2.537545e+06
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 1.1162672e+07
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 5.086684e+07
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 7.6439552e+07
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 5.6336384e+07
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 272983
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 7.6414976e+07
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 1.32775936e+08
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.6773376622380586e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 2.810528e+06
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 14400
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 15600
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 484320
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 897600
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 9.454456e+07
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 2.263755e+06
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 1.441792e+06
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 1.441792e+06
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.48588576e+08
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 17
# HELP photoprism_build_info information about the photoprism instance
# TYPE photoprism_build_info gauge
photoprism_build_info{edition="ce",goversion="go1.20.1",version="230225-ab5ffe18a-Linux-AMD64-DEBUG"} 1
# HELP photoprism_statistics_media_count media statistics for this photoprism instance
# TYPE photoprism_statistics_media_count gauge
photoprism_statistics_media_count{stat="albums"} 0
photoprism_statistics_media_count{stat="all"} 0
photoprism_statistics_media_count{stat="files"} 0
photoprism_statistics_media_count{stat="folders"} 0
photoprism_statistics_media_count{stat="photos"} 0
photoprism_statistics_media_count{stat="videos"} 0
```

<!--

Thank you for your interest in contributing!

Because we want to create the best possible product for our users, we have a set of criteria to ensure that all submissions are acceptable, see https://docs.photoprism.app/developer-guide/pull-requests/ for details.

(1) Please provide a concise description of your pull request.

- What does it implement / fix / improve? Why?
- Are the changes related to an existing issue?

(2) After you submit your first pull request, you will be asked to accept our CLA, see https://www.photoprism.app/cla.

(3) Finally, please confirm that the following criteria are met by replacing "[ ]" with "[x]" (also possible at a later time).

-->

Acceptance Criteria:

- [x] Features and enhancements must be fully implemented so that they can be released at any time without additional work
- [x] Automated unit and/or acceptance tests are mandatory to ensure the changes work as expected and to reduce repetitive manual work
- [x] Frontend components must be responsive to work and look properly on phones, tablets, and desktop computers; you must have tested them on all major browsers and different devices
- [x] Documentation and translation updates should be provided if needed
- [x] In case you submit database-related changes, they must be tested and compatible with SQLite 3 and MariaDB 10.5.12+

<!--

Since reviewing, testing and finally merging pull requests requires significant resources on our side, this can take several months if it's not just a small fix, especially if extensive testing is required to prevent bugs from getting into our stable version.

We thank you for your patience! :)

-->

### CODE REVIEW

**Comment by brandon1024** [comment]
`@maintainers`, what's the process for documentation? I don't think there's any internal documentation needed here, but it might be a good idea to add some information in the user docs. What are your thoughts?

**Comment by graciousgrey** [comment]
Thank you very much for your efforts, we will look into this as soon as our time permits.

**Comment by brandon1024** [comment]
@lastzero do you know why the security job is failing? I don't have access to the details of the task so I cannot fix whatever it's looking for.

Also these changes often have conflicts in the `mod`/`sum`. I'll rebase once the review is underway.

**Comment by lastzero** [comment]
Might be some dependency or unsafe logging (see log4j vulnerability). Couldn't see any details, but maybe that's because I'm on my phone...

**Comment by brandon1024** [comment]
I'll need to rebase this to the tip of main, now that the latest milestone release is out the door.

@lastzero will these changes be impacted by the user management and authentication features introduced in the latest milestone? I think it should be ok, those statistics were part of the read-only public API. Do you know if those APIs will remain open, or are there plans to secure them?

**Comment by lastzero** [comment]
@brandon1024 Thank you for staying on top of this! I apologize for not getting back to you sooner. We had to focus all our resources on the release and then needed a break.

- [ ] Once all merge conflicts are resolved, I should be able to merge this after a quick security audit.... Other bugs can easily be fixed later if needed. However, it is important that we do not accidentally introduce any attack vectors as some users have connected our software directly to the Internet.
- [ ] In addition, a few lines of documentation with specific usage examples and compatibility information seem important to release this to everyone. I will be happy to help with finalizing it if you provide me with a draft.

**Comment by lastzero** [comment]
I'll be happy to merge this once there are no more conflicts and I have your go! :+1:

**Comment by lastzero** [comment]
@brandon1024 Unfortunately we haven't received any feedback (which is partly our fault for being so slow), so I'm closing this PR for now. I'd still like to merge your changes once the conflicts are resolved! :)

**Pull request closed without merging**
