### PR TITLE
Upgrade to RawTherapee 5.9 for docker-develop-jammy only

### PR DESCRIPTION
**Pull request by mmaravillo**
For issue #2291.

This patch will upgrade RawTherapee to 5.9 on "make docker-develop-jammy".

Tested locally on x64 build.

<code>
mike@WALNUT:~/build/photoprism$ docker image ls
REPOSITORY           TAG               IMAGE ID       CREATED          SIZE
photoprism/develop   230114-jammy      8cfeec53e49d   13 minutes ago   3.37GB
photoprism/develop   jammy             8cfeec53e49d   13 minutes ago   3.37GB
photoprism/develop   latest            8cfeec53e49d   13 minutes ago   3.37GB
photoprism/develop   ubuntu            8cfeec53e49d   13 minutes ago   3.37GB
photoprism/develop   230111-jammy      49c3e0cdf321   2 days ago       3.35GB
moby/buildkit        buildx-stable-1   76ecf3f0f41a   4 days ago       168MB
ubuntu               jammy             4c2c87c6c36e   5 weeks ago      69.2MB
mike@WALNUT:~/build/photoprism$ head -2 Dockerfile
# Ubuntu 22.04 LTS (Jammy Jellyfish)
FROM photoprism/develop:230114-jammy
mike@WALNUT:~/build/photoprism$ docker compose build
[+] Building 2.7s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                   0.0s
 => => transferring dockerfile: 32B                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                      0.0s
 => => transferring context: 35B                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/photoprism/develop:230114-jammy                                                                                                             0.0s
 => [1/4] FROM docker.io/photoprism/develop:230114-jammy                                                                                                                               0.0s
 => [internal] load build context                                                                                                                                                      0.1s
 => => transferring context: 741.26kB                                                                                                                                                  0.1s
 => CACHED [2/4] WORKDIR /go/src/github.com/photoprism/photoprism                                                                                                                      0.0s
 => [3/4] COPY . .                                                                                                                                                                     1.6s
 => [4/4] COPY --chown=root:root /scripts/dist/ /scripts/                                                                                                                              0.1s
 => exporting to image                                                                                                                                                                 0.9s
 => => exporting layers                                                                                                                                                                0.8s
 => => writing image sha256:8ffaee2dc0d0679b1b543761a502d8dd8c04efb7d381cbfc34206518cb2d261b                                                                                           0.0s
 => => naming to docker.io/photoprism/photoprism:develop                                                                                                                               0.0s
mike@WALNUT:~/build/photoprism$ docker compose up -d
[+] Running 1/1
 ⠿ Container photoprism-photoprism-1  Started                                                                                                                                          0.4s
mike@WALNUT:~/build/photoprism$ make terminal
docker compose exec -u 1000 photoprism bash
photoprism@230114-jammy:/go/src/github.com/photoprism/photoprism$ rawtherapee -v
RawTherapee, version 5.9
photoprism@230114-jammy:/go/src/github.com/photoprism/photoprism$
</code>

Acceptance Criteria:

- [ ] **Features and enhancements are fully implemented** so that they can be released at any time without additional work
- [ ] **Automated unit and/or acceptance tests have been added** to ensure the changes work as expected and to reduce repetitive manual work
- [ ] **User interface changes are fully responsive** and have been tested on all major browsers and various devices
- [ ] Database-related changes are compatible with SQLite and MariaDB
- [ ] Translations have been / will be updated (specify if needed)
- [ ] Documentation has been / will be updated (specify if needed)
- [ ] Contributor License Agreement (CLA) has been signed

### CODE REVIEW

**Comment by lastzero** [comment]
Thanks for adding an install script for RawTherapee! I was also thinking about this yesterday, but wasn't quite sure:

- Is it safe to simply use packages from a newer distribution? What does the documentation say about this?
- I also believe that there is a safer way to add additional upstream repositories so that they get a lower priority, causing "apt upgrade" and even "install" to ignore them unless you pass a specific parameter.
- Of course, before we can merge / offer this, it needs to be tested and working on ARM and ARM64 too.

**Comment by mmaravillo** [comment]
> Thanks for adding an install script for RawTherapee! I was also thinking about this yesterday, but wasn't quite sure:

You're welcome!  Will try to make small contributions as time permits. :)

> * Is it safe to simply use packages from a newer distribution? What does the documentation say about this?

Should be safe I believe, as long as the dependencies that get installed don't include major packages like glibc.

I did a quick check on the dependencies that the new rawtherapee brought along in the manual apt install on #2291.
https://bugs.launchpad.net/ubuntu/+source/rawtherapee
https://bugs.launchpad.net/ubuntu/+source/atkmm1.6
https://bugs.launchpad.net/ubuntu/+source/cairomm
https://bugs.launchpad.net/ubuntu/+source/glibmm2.4
https://bugs.launchpad.net/ubuntu/+source/gtkmm2.4
https://bugs.launchpad.net/ubuntu/+source/lensfun
https://bugs.launchpad.net/ubuntu/+source/pangomm

> * I also believe that there is a safer way to add additional upstream repositories so that they get a lower priority, causing "apt upgrade" and even "install" to ignore them unless you pass a specific parameter.

Yup, I have heard but haven't tried it though. So Google brought me here, https://help.ubuntu.com/community/PinningHowto

The information seems to apply still as of today even though it references old Ubuntu distros.
Confirmed with "man apt_preferences" on Ubuntu 22.10.

> * Of course, before we can merge / offer this, it needs to be tested and working on ARM and ARM64 too.

Currently spinning one on a vm running on RPi4 ESXi:

msvadm@msvadm:~/build/photoprism$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10"
msvadm@msvadm:~/build/photoprism$ uname -a
Linux msvadm 5.19.0-26-generic #27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:49:05 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
msvadm@msvadm:~/build/photoprism$ time make docker-develop-jammy
docker pull --platform=arm64 ubuntu:jammy
jammy: Pulling from library/ubuntu
10175de2f0c4: Pull complete
Digest: sha256:27cb6e6ccef575a4698b66f5de06c7ecd61589132d5a91d098f7f3f9285415a9
Status: Downloaded newer image for ubuntu:jammy
docker.io/library/ubuntu:jammy
scripts/docker/buildx-multi.sh develop linux/arm64 jammy /jammy "-t photoprism/develop:latest -t photoprism/develop:ubuntu"
...

**Comment by lastzero** [comment]
(1) Be aware that some of our users run this on startup with `PHOTOPRISM_INIT: "update"`:

https://github.com/photoprism/photoprism/blob/aa63a4408f83703669581f25de670f012e46971d/scripts/dist/Makefile#L7-L9

This looks like it could cause all packages to be updated in combination with adding the upstream apt repos?

(2) Also, compiled binaries would no longer work if the glibc version was updated in the newer distribution (as it contains an explicit version check), but not necessarily otherwise as long as all other libraries are compatible (they generally do not come with explicit version or compatibility checks).

Since additional libraries like libraw are usually dynamically linked, I'm afraid the only way to know for sure would be to test "all" functionality, i.e. process all file formats and see if this works - which is not feasible. Also, the Ubuntu team might update glibc, which would unexpectedly break the package for us.

If I'm right about this and we want/need a new RawTherapee right away, it might be better to build our own RawTherapee version from source. It's still a bit of work, but not as much as testing each format and package update individually... However, if someone knows more about package compatibility than I do and can explain why we should not worry at all, I'm happy to learn!

**Comment by mmaravillo** [comment]
We should be safe now with 422ce8b.  The apt pinning will make the OS stay in jammy even with `apt upgrade` or `apt dist-upgrade`.

Sample manual session:
```
mike@WALNUT:~/build/photoprism$ docker image ls
REPOSITORY              TAG               IMAGE ID       CREATED          SIZE
photoprism/photoprism   develop           3d270ebc3da7   47 seconds ago   3.46GB
photoprism/develop      230114-jammy      7c9fab47abe8   10 minutes ago   3.24GB
photoprism/develop      jammy             7c9fab47abe8   10 minutes ago   3.24GB
photoprism/develop      latest            7c9fab47abe8   10 minutes ago   3.24GB
photoprism/develop      ubuntu            7c9fab47abe8   10 minutes ago   3.24GB
moby/buildkit           buildx-stable-1   76ecf3f0f41a   4 days ago       168MB
ubuntu                  jammy             6b7dfa7e8fdb   5 weeks ago      77.8MB
mike@WALNUT:~/build/photoprism$ docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
mike@WALNUT:~/build/photoprism$ docker compose build
[+] Building 0.2s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                   0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                      0.0s
 => => transferring context: 35B                                                                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/photoprism/develop:230114-jammy                                                                                                                                                             0.0s
 => [1/4] FROM docker.io/photoprism/develop:230114-jammy                                                                                                                                                                               0.0s
 => [internal] load build context                                                                                                                                                                                                      0.1s
 => => transferring context: 246.05kB                                                                                                                                                                                                  0.1s
 => CACHED [2/4] WORKDIR /go/src/github.com/photoprism/photoprism                                                                                                                                                                      0.0s
 => CACHED [3/4] COPY . .                                                                                                                                                                                                              0.0s
 => CACHED [4/4] COPY --chown=root:root /scripts/dist/ /scripts/                                                                                                                                                                       0.0s
 => exporting to image                                                                                                                                                                                                                 0.0s
 => => exporting layers                                                                                                                                                                                                                0.0s
 => => writing image sha256:3d270ebc3da712a72223927354d747df1c25076e417018dd552f0359393e5f8c                                                                                                                                           0.0s
 => => naming to docker.io/photoprism/photoprism:develop                                                                                                                                                                               0.0s
mike@WALNUT:~/build/photoprism$ docker compose up -d
[+] Running 2/2
 ⠿ Network photoprism_default         Created                                                                                                                                                                                          0.1s
 ⠿ Container photoprism-photoprism-1  Started                                                                                                                                                                                          0.5s
mike@WALNUT:~/build/photoprism$ make root-terminal
docker compose exec -u root photoprism bash
root@230114-jammy:/go/src/github.com/photoprism/photoprism$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
root@230114-jammy:/go/src/github.com/photoprism/photoprism$ apt update
Get:1 https://deb.nodesource.com/node_18.x jammy InRelease [4563 B]
Get:2 https://deb.nodesource.com/node_18.x jammy/main amd64 Packages [774 B]
Get:3 https://dl.google.com/linux/chrome/deb stable InRelease [1811 B]
Get:4 https://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1075 B]
Get:5 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:6 https://dlm.mariadb.com/repo/mariadb-server/10.10/repo/ubuntu jammy InRelease [7761 B]
Get:7 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:9 https://dlm.mariadb.com/repo/maxscale/latest/apt jammy InRelease [9335 B]
Get:10 http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_22.04  InRelease [1530 B]
Get:11 https://dlm.mariadb.com/repo/mariadb-server/10.10/repo/ubuntu jammy/main/debug arm64 Packages [11.4 kB]
Get:12 https://dlm.mariadb.com/repo/mariadb-server/10.10/repo/ubuntu jammy/main amd64 Packages [14.7 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [659 kB]
Get:14 https://dlm.mariadb.com/repo/mariadb-server/10.10/repo/ubuntu jammy/main arm64 Packages [14.3 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]
Get:16 http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_22.04  Packages [2277 B]
Get:8 https://downloads.mariadb.com/Tools/ubuntu jammy InRelease [2161 B]
Get:17 https://downloads.mariadb.com/Tools/ubuntu jammy/main amd64 Packages [1244 B]
Get:18 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Get:19 https://dlm.mariadb.com/repo/mariadb-server/10.10/repo/ubuntu jammy/main/debug amd64 Packages [15.4 kB]
Get:20 https://dlm.mariadb.com/repo/maxscale/latest/apt jammy/main amd64 Packages [1433 B]
Get:21 http://archive.ubuntu.com/ubuntu lunar InRelease [267 kB]
Get:22 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [720 kB]
Get:23 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [4732 B]
Get:24 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [786 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:27 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:28 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:29 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [990 kB]
Get:30 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1035 kB]
Get:31 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [708 kB]
Get:32 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [8978 B]
Get:33 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [7286 B]
Get:34 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [3520 B]
Get:35 http://archive.ubuntu.com/ubuntu lunar/universe amd64 Packages [18.4 MB]
Get:36 http://archive.ubuntu.com/ubuntu lunar/main amd64 Packages [1783 kB]
Fetched 45.8 MB in 22s (2057 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
root@230114-jammy:/go/src/github.com/photoprism/photoprism$ apt dist-upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@230114-jammy:/go/src/github.com/photoprism/photoprism$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
root@230114-jammy:/go/src/github.com/photoprism/photoprism$ rawtherapee -v
RawTherapee, version 5.9
root@230114-jammy:/go/src/github.com/photoprism/photoprism$
```

**Comment by lastzero** [comment]
Thanks a lot! I will try these changes when I have some time next week.

**Comment by mmaravillo** [comment]
Done with test build on arm64.

```
mike@msvadm:~/build/photoprism$ uname -a
Linux msvadm 5.19.0-29-generic #30-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 4 12:32:16 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
mike@msvadm:~/build/photoprism$ docker images "photoprism/*"
REPOSITORY              TAG            IMAGE ID       CREATED          SIZE
photoprism/photoprism   develop        447aae199499   29 minutes ago   2.86GB
photoprism/develop      230114-jammy   bbe4b28fbea4   57 minutes ago   2.64GB
photoprism/develop      jammy          bbe4b28fbea4   57 minutes ago   2.64GB
photoprism/develop      latest         bbe4b28fbea4   57 minutes ago   2.64GB
photoprism/develop      ubuntu         bbe4b28fbea4   57 minutes ago   2.64GB
mike@msvadm:~/build/photoprism$ docker compose build
[+] Building 35.0s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                      0.1s
 => => transferring dockerfile: 547B                                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                                         0.0s
 => => transferring context: 337B                                                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/photoprism/develop:230114-jammy                                                                                                                                0.0s
 => [1/4] FROM docker.io/photoprism/develop:230114-jammy                                                                                                                                                  0.0s
 => [internal] load build context                                                                                                                                                                        14.0s
 => => transferring context: 218.43MB                                                                                                                                                                    14.0s
 => CACHED [2/4] WORKDIR /go/src/github.com/photoprism/photoprism                                                                                                                                         0.0s
 => [3/4] COPY . .                                                                                                                                                                                       13.0s
 => [4/4] COPY --chown=root:root /scripts/dist/ /scripts/                                                                                                                                                 0.1s
 => exporting to image                                                                                                                                                                                    7.4s
 => => exporting layers                                                                                                                                                                                   7.4s
 => => writing image sha256:8bdfb1d29d47ab6e7ab229a57dcaff6b3e6c224f68d203d9772213db7de9ee43                                                                                                              0.0s
 => => naming to docker.io/photoprism/photoprism:develop                                                                                                                                                  0.0s
mike@msvadm:~/build/photoprism$ docker compose up -d
[+] Running 2/2
 ⠿ Network photoprism_default         Created                                                                                                                                                             0.2s
 ⠿ Container photoprism-photoprism-1  Started                                                                                                                                                             1.2s
mike@msvadm:~/build/photoprism$ make root-terminal
docker compose exec -u root photoprism bash
root@230114-jammy:/go/src/github.com/photoprism/photoprism$ uname -a
Linux 905eb6a7a4ef 5.19.0-29-generic #30-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 4 12:32:16 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
root@230114-jammy:/go/src/github.com/photoprism/photoprism$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
root@230114-jammy:/go/src/github.com/photoprism/photoprism$ apt update
Get:1 https://deb.nodesource.com/node_18.x jammy InRelease [4563 B]
Get:2 http://ports.ubuntu.com/ubuntu-ports jammy InRelease [270 kB]
Get:3 https://dlm.mariadb.com/repo/mariadb-server/10.10/repo/ubuntu jammy InRelease [7761 B]
Get:4 https://dlm.mariadb.com/repo/maxscale/latest/apt jammy InRelease [9335 B]
Get:5 https://dlm.mariadb.com/repo/mariadb-server/10.10/repo/ubuntu jammy/main amd64 Packages [14.7 kB]
Get:6 https://deb.nodesource.com/node_18.x jammy/main arm64 Packages [774 B]
Get:7 https://dlm.mariadb.com/repo/mariadb-server/10.10/repo/ubuntu jammy/main/debug arm64 Packages [11.4 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease [114 kB]
Get:9 https://dlm.mariadb.com/repo/mariadb-server/10.10/repo/ubuntu jammy/main arm64 Packages [14.3 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease [99.8 kB]
Get:11 https://dlm.mariadb.com/repo/mariadb-server/10.10/repo/ubuntu jammy/main/debug amd64 Packages [15.4 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease [110 kB]
Get:13 https://dlm.mariadb.com/repo/maxscale/latest/apt jammy/main amd64 Packages [1433 B]
Get:14 http://ports.ubuntu.com/ubuntu-ports lunar InRelease [267 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 Packages [1758 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports jammy/restricted arm64 Packages [24.2 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports jammy/multiverse arm64 Packages [224 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports jammy/universe arm64 Packages [17.2 MB]
Get:19 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 Packages [937 kB]
Get:20 http://ports.ubuntu.com/ubuntu-ports jammy-updates/restricted arm64 Packages [295 kB]
Get:21 http://ports.ubuntu.com/ubuntu-ports jammy-updates/multiverse arm64 Packages [3452 B]
Get:22 http://ports.ubuntu.com/ubuntu-ports jammy-updates/universe arm64 Packages [852 kB]
Get:23 http://ports.ubuntu.com/ubuntu-ports jammy-backports/main arm64 Packages [3511 B]
Get:24 http://ports.ubuntu.com/ubuntu-ports jammy-backports/universe arm64 Packages [7297 B]
Get:25 http://ports.ubuntu.com/ubuntu-ports jammy-security/universe arm64 Packages [653 kB]
Get:26 http://ports.ubuntu.com/ubuntu-ports jammy-security/restricted arm64 Packages [282 kB]
Get:27 http://ports.ubuntu.com/ubuntu-ports jammy-security/main arm64 Packages [634 kB]
Get:28 http://ports.ubuntu.com/ubuntu-ports lunar/main arm64 Packages [1755 kB]
Get:29 http://ports.ubuntu.com/ubuntu-ports lunar/universe arm64 Packages [18.2 MB]
Fetched 43.8 MB in 14s (3208 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
root@230114-jammy:/go/src/github.com/photoprism/photoprism$ apt dist-upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@230114-jammy:/go/src/github.com/photoprism/photoprism$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
root@230114-jammy:/go/src/github.com/photoprism/photoprism$ rawtherapee -v
RawTherapee, version 5.9
root@230114-jammy:/go/src/github.com/photoprism/photoprism$
```

**Comment by lastzero** [comment]
Since we will be upgrading to the new Ubuntu version, we will not (have to) merge this. Thank you very much for your efforts! Much appreciated.

**Comment by lastzero** [comment]
See:
- #3305

**Pull request closed without merging**
