### PR TITLE
Give the photoprism service the standard name photoprism 

### PR DESCRIPTION
**Pull request by zierbeek**
Add container_name to the docker-compose file, making it easier to setup other services who rely on the container name and making it easier for things like docker restart, docker log ,...

### CODE REVIEW

**Comment by lastzero** [comment]
Wound't this cause issues when running multiple instances on the same server?

**Comment by zierbeek** [comment]
Hmm indeed, is there a case when people run multiple instances?

________________________________
Van: Michael Mayer ***@***.***>
Verzonden: dinsdag 4 mei 2021 11:23
Aan: photoprism/photoprism ***@***.***>
CC: zierbeek ***@***.***>; Author ***@***.***>
Onderwerp: Re: [photoprism/photoprism] Give the photoprism service the standard name photoprism (#1257)


Wound't this cause issues when running multiple instances on the same server?

**Comment by lastzero** [comment]
> Hmm indeed, is there a case when people run multiple instances?

Yes, some users do this.

You can refer to the container via `docker-compose [command] photoprism` instead, container name is mainly useful when using the docker command directly from my experience.

**Comment by lastzero** [comment]
You think we should still add it in this case? I'm afraid that it causes errors for users with more instances... going to ask for support and/or we need to add more docs...

**Comment by zierbeek** [comment]
Yes perfect, for this case it could be good for using SWAG. Since it took me a while to fix it for swag. I Will add some info in the docs. Now it used docker rename.
________________________________
Van: Michael Mayer ***@***.***>
Verzonden: dinsdag 4 mei 2021 19:14
Aan: photoprism/photoprism ***@***.***>
CC: zierbeek ***@***.***>; Author ***@***.***>
Onderwerp: Re: [photoprism/photoprism] Give the photoprism service the standard name photoprism (#1257)


You think we should still add it in this case? I'm afraid that it causes errors for users with more instances... going to ask for support and/or we need to add more docs...

**Comment by lastzero** [comment]
Alright, I'll close this then... thank you!

**Pull request closed without merging**
