### PR TITLE
Places: Fix cluster update callback function

### PR DESCRIPTION
**Pull request by reubendowle**
This is an attempt to fix the latest issues noted where the places photo clusters (https://github.com/photoprism/photoprism/issues/1187) can sometimes render in wrong locations etc.

It looks like the reason this sometimes occurs is that the cluster updates happen in an asyncronous callback, and that processing can be triggered multiple times in parallel in some cases if the processing takes longer than the time between multiple map events.

This is difficult to reliably reproduce, however I have been unable to reproduce any issues since making this change.

When testing, I consistently saw a cluster from USA appear when zooming into Tübingen:

image

With the fixed code, this consistently renders correctly:

image

Acceptance Criteria:

- [ ] Features and enhancements must be fully implemented so that they can be released at any time without additional work
- [ ] Automated unit and/or acceptance tests are mandatory to ensure the changes work as expected and to reduce repetitive manual work
- [ ] Frontend components must be responsive to work and look properly on phones, tablets, and desktop computers; you must have tested them on all major browsers and different devices
- [ ] Documentation and translation updates should be provided if needed
- [ ] In case you submit database-related changes, they must be tested and compatible with SQLite 3 and MariaDB 10.5.12+

### CODE REVIEW

**Comment by lastzero** [comment]
Thanks! I'll give that a try :)

From how the cluster update code looks, one problem could be that it is a "two-pass" approach where the features are queried multiple times, i.e. first the cluster ids and then the related images via `getMultipleClusterFeatures()`, so the data could have changed in between? 🤔

**Comment by lastzero** [comment]
@reubendowle Feel free to email us if you would like to join our Contributors Chat! 💬

**Comment by lastzero** [comment]
Works locally, although it's hard to see if everything is correct because I have too many pictures...

@reubendowle @heikomat I've started a new preview build so you can [test it in our demo](https://demo.photoprism.app/library/places). It's easy to see there if the number of pictures in the clusters adds up when zooming in and out! :nerd_face:

**Comment by lastzero** [comment]
@reubendowle One thing I noticed is that when I zoom or move the map, the clusters don't update simultaneously and even after I stop doing anything, it can take a while for the new clusters to be visible and the old ones to disappear. With your changes, would it help to also listen for the `move` event instead of just `moveend`? Based on my tests, it hasn`t made any difference so far (just caused more computational overhead).

**Comment by reubendowle** [comment]
> One thing I noticed is that when I zoom or move the map, the clusters don't update simultaneously and even after I stop doing anything, it can take a while for the new clusters to be visible and the old ones to disappear. With your changes, would it help to also listen for the move event instead of just moveend? Based on my tests, it hasn`t made any difference so far (just caused more computational overhead).

In theory if the time it takes to update the clusters is very short, then implementing move would be a good idea. This fires multiple times as the map is scrolling, zooming, etc, so would allow the clusters to stay closely in sync with the map itself.

But if the processing time is longer, then you might just end up taking longer to get to the final clusters when the zooming has stopped - if the processing of clusters for an intermediary map step delays the processing for the final map step.

I really don't know what the best answer is here. Perhaps on fast desktops move might be good, and perhaps on mobile it would be worse. But the only way to know properly would be with a lot of testing. So I think just updating once on moveend is probably good as a safer/conservative option unless we are sure the other way is better.

**Pull request merged**
