### PR TITLE
Support .mts and .mpo files

### PR DESCRIPTION
**Pull request by kvalev**

### CODE REVIEW

**Comment by alexislefebvre** [comment]
Can your browser read these files?

**Comment by lastzero** [comment]
Thanks! What are these file types used for?

**Comment by kvalev** [comment]
`mts` is a video format and `mpo` is a stereoscopic image format, that contains 3D images

**Comment by lastzero** [comment]
Can PhotoPrism display / index those? What happens if you add them?

**Comment by kvalev** [comment]
Yeah it seems so. I guess the underlying framework supports both formats. Videos are detected and shown correctly. The `mpo` file is essentially a wrapper for two (or more) stereo images. Here only the first one is read, but that is good enough for me, as I dont think it is possible/easy to actually show a 3D image.

**Pull request merged**
